### ISSUE TITLE
def get_var_by_op(self, op)

### ISSUE THREAD

**Issue by leosk-knight** [Tencent/PocketFlow#101]
I saw that we get the var by judging whether the name contains “weight” or “bias”。
if ‘weight’ in wtensor.name or ‘bias’ in wtensor.name 
But if my model is not so named, I can't get the corresponding tensor, so I want to ask if these algorithms can only target the models you have already written.

**Comment by jiaxiang-wu** [comment]
In `ChannelPrunedLearner`, variables are recognized by their names and it is possible that your self-defined model cannot be correctly parsed. In other learners, *e.g.* `ChannelPrunedGpuLearner` and `DisChnPrunedLearner`, variables are recognized by their related TensorFlow operations, which should be more flexible.

**Comment by leosk-knight** [comment]
Thank you for your reply. If I want to calculate flops by op and get the weight of op, is there any general method?

**Comment by jiaxiang-wu** [comment]
1. Sorry, I do not know which method can be used to get FLOPs by op.
2. You can traverse `op.inputs`, which is a list of tensors, to get its weight tensor.

**Comment by leosk-knight** [comment]
Ok, this project has helped me a lot, thanks
