### ISSUE TITLE
Can PocketFlow be applied to ResNet-50 whose parameters have been modified and then be trained to do other works instead of classification? 

### ISSUE THREAD

**Issue by HandsomeRocketboy** [Tencent/PocketFlow#103]
I want to use PocketFlow to speed up my own network which is modified from ResNet-50, for it can be applyed on my drone.But I don't know how can I do it. 

By the way, the network is not used on ImageNet for classification.

**Comment by jiaxiang-wu** [comment]
@HandsomeRocketboy Is it duplicate with issue #104? If so, can you close one of these two issues?

**Comment by HandsomeRocketboy** [comment]
Yes, of course, I have closen the latter just now. Sorry for forgotten to delete the other one.

**Comment by jiaxiang-wu** [comment]
What is the task for ResNet-50 model? Regression? Classification? Object Detection?

**Comment by HandsomeRocketboy** [comment]
Monocular Depth Esitimation, and the training is unsupervised.

**Comment by jiaxiang-wu** [comment]
The training is unsupervised? How do you train the model then?

**Comment by HandsomeRocketboy** [comment]
Thanks for your help, I will follow this.
