### ISSUE TITLE
Some questions about Channel Pruning Auto

### ISSUE THREAD

**Issue by buryang** [Tencent/PocketFlow#107]
Hi, I‘m trying to compress my Unet network which for regression. I just use 1-lambda*l2_loss for Acc, and till now trained 40 roll outs，the Acc reach only 0.22 but the Acc of original model is 0.96， is it
 normal? In addition, the hidden layer size in the AMC paper is 300, why is your code changed to 64? 
Then sckit-learn training is slow, can you save the intermediate checkpoints of actor-critic models?

**Comment by jiaxiang-wu** [comment]
@psyyz10 Could you please take a look at this issue?

**Comment by psyyz10** [comment]
@buryang 

1. If you choose the auto mode, rl agent will start to learn from the 50 roll out. Hence before the 50 roll out, the agent will random choose split ratio. Or you can set `--cp_nb_rlouts_ming` to other value.
2. If you choose the auto model of channel pruning, please set `--ddpg_noise_std_init=0.5 `.
3. After 200 roll outs, the network will be retrained, so the Acc will be improved again.
4. What's your hidden layer size in AMC means? Our approach may be different from AMC.
5. You can save the intermediate results by setting `--cp_nb_rlouts` to a smaller value.

**Comment by buryang** [comment]
4.  AMC: AutoML for Model Compression and Acceleration on Mobile Devices.

**Comment by psyyz10** [comment]
@buryang I know that paper, but what the hidden layer size means? Maybe we do not used that variable.

**Comment by Jinyyyy** [comment]
@psyyz10 

Hi, thanks for your open-source code.

1. In the ChannelPruning Auto, which channel pruning method are you using? 
    The original AMC paper prune the channels in the convolutional kernel with lowest magnitude.
    It seems that you use LASSO to select the channels. Please correct me if I misunderstand the code.

2. In the channel-pruning-gpu repo, you implement the discrimination-aware channel pruning. Do you 
    have the implementation of LASSO based channel pruning on GPU?

Thanks.
