### ISSUE TITLE
Support pose estimate model?

### ISSUE THREAD

**Issue by sunpangu** [Tencent/PocketFlow#108]
I have read an article that PocketFlow could accelerate pose estimate model 3 times speed. Can we use this function now?

**Comment by jiaxiang-wu** [comment]
What is your pose estimation model's architecture and training method? Self-defined models can be manually added, following this [tutorial](https://pocketflow.github.io/self_defined_models/).

**Comment by sunpangu** [comment]
> What is your pose estimation model's architecture and training method? Self-defined models can be manually added, following this [tutorial](https://pocketflow.github.io/self_defined_models/).

Just like Openpose and Alphapose. What's your model in this article[http://it.sohu.com/20181105/n554400817.shtml](url)?Would you share this pretrain model.

**Comment by jiaxiang-wu** [comment]
@sunpangu 
Sorry, we cannot release that pre-trained model, since it belongs to other projects. You can try to add your pose estimation model following the tutorial mentioned above.
