### ISSUE TITLE
Support for 1D convolutions

### ISSUE THREAD

**Issue by dorian95** [Tencent/PocketFlow#11]
I was wondering if PocketFlow supports 1D convolutions. If not, how could this functionality be added? I want to compress a CNN with 1D convolutions for string classification.

**Comment by jiaxiang-wu** [comment]
Hi, which of the following two do you mean?
1. The original network consists of 2D convolutions, and can be compressed with 2 layers of 1D- convolution.
2. The original network consists of 1D convolutions.

**Comment by dorian95** [comment]
2. The original network consists of 1D convolutions.

**Comment by jiaxiang-wu** [comment]
We do not have a plan to support such feature for the moment. You may implement it by yourself and create a pull request to PocketFlow. You contribution will be greatly appreciated.
