### ISSUE TITLE
The mode of fine tune

### ISSUE THREAD

**Issue by as754770178** [Tencent/PocketFlow#110]
When `uql_use_buckets` is True in UniformQuantLearner, PocketFlow how to fine tune the parameter in current bucket? Will it record the output before this bucket to avoid repeated calculation?

**Comment by haolibai** [comment]
What do you mean by "record the output before this bucket to avoid repeated calculation"?

Generally the computational graph of quantization with bucketing is built as follows:
1) Cut the weights into multiple pieces (buckets);
2) Quantize each buckets according to some rules (uniform/nonuniform), and set up its parameters (e.g., min/max values);
3) Reshape the weights back to its original shape;

In the forward pass, the parameters of each buckets are computed, which is a necessary step to get the quantized weights. In the backward pass, the full-precision weights are updated, which allows for updating the bucket parameters in the next forward pass.

**Comment by as754770178** [comment]
Such as finetunning, if I only want to change the net constructure after the fourth layer, that is the output of fourth layer is not changed. Record the output of the fourth layer to avoid repeated calculation.

**Comment by as754770178** [comment]
ok, thanks
