### ISSUE TITLE
Unable to generate .pb files for non-uniform quantization

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#112]
**Describe the bug**
I run quantization script on resnet a defined in documentation with command line argument to limit training to 0.01 %. When i try to run the script to convert it to .pb file, i get the following error

``UnboundLocalError: local variable 'file_path' referenced before assignment``

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by haolibai** [comment]
Hi. Currently `UniformQuantLearner` and `NonUniformQuantLearner` may not support the conversion to `.pb` and `.tflite` formats, as they are more research-oriented for now. We will improve their deployment on end devices in the following versions. To export the quantized model to `.pb` and `.tflite` formats, please use `UniformQuantTFLearner`. Thanks.

**Comment by dhingratul** [comment]
How do you benchmark the results then ?

**Comment by jiaxiang-wu** [comment]
@dhingratul We only evaluate the inference speed-up for uniform quantization models, generated by `UniformQuantTFLearner`.
