### ISSUE TITLE
Weight Sparsification stuck

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#116]
**Describe the bug**
When i resume weight sparsification for Resnet model, it gets stuck at the following:

```
97] Filling up shuffle buffer (this may take a while): 1 of 1024
2018-11-30 14:53:20.702344: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:135] Shuffle buffer filled.
```

 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jiaxiang-wu** [comment]
Hi, could you please post the execution command and more complete log (including the FLAGS's values part)?

**Comment by dhingratul** [comment]
Fixed after restart
