### ISSUE TITLE
WeightSparseLearner  problem

### ISSUE THREAD

**Issue by leosk-knight** [Tencent/PocketFlow#117]
Hi，When I use the weightsparse(optimal) compression model, I find that many times after the FT, the acc and reward are reduced, and the final convergence ratio of each layer is not reasonable. The training parameters I use: ./scripts/run_local.py nets/resnet_at_ilsvrc12_run.py —learner weight-sparse —resnet_size 18 —ws_prune_ratio_prtl optimal —ws_prune_ratio 0.6

**Comment by jiaxiang-wu** [comment]
@leosk-knight 
Hi, can you post the log for accuracy and reward before and after fine-tuning?

**Comment by leosk-knight** [comment]
It is not very convenient, because it is training in the company's internal network. The main problem is that the fine-tuned reward is smaller than the previous reward. I also tested on cifar10, the same conditions have been tested many times, the convergence results are somewhat different, but the results are better than imagenet

**Comment by jiaxiang-wu** [comment]
Are you concerning that the log may contain some sensitive information about your company? There should not be any. If so, can you try to remove such information and post the remaining log? It is hard to tell what went wrong only based on your description.

**Comment by jiaxiang-wu** [comment]
@leosk-knight Any updates?
