### ISSUE TITLE
Does PocketFlow support training/pruning on local with more than one GPU?

### ISSUE THREAD

**Issue by jiaxiangxu** [Tencent/PocketFlow#124]

**Comment by jiaxiang-wu** [comment]
Yes, if you have installed horovod in the local environment, instead of running it in a docker image.

**Comment by jiaxiangxu** [comment]
Excuse me, does it mean that I can install horovod in the existing docker environment and then I can use run_local.sh to train/prune with more than one GPUs on one desktop?

**Comment by jiaxiang-wu** [comment]
If you are using horovod from docker, then you should start the docker environment with `scripts/run_docker.sh` and then use `main.sh` to start PocketFlow's training code.
