### ISSUE TITLE
UnboundLocalError: local variable 'file_path' referenced before assignment

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#125]
**Describe the bug**
1. Train Weight Sparsification with 0.01 % epochs
2. Use the script from tutorial to convert it to a .pb file

Error: UnboundLocalError: local variable 'file_path' referenced before assignment

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jiaxiang-wu** [comment]
@dhingratul The compressed model generated by `WeightSparseLearner` does not support exporting to TensorFlow Lite, since sparse matrix multiplication is not supported by TensorFlow Lite, as far as I know. Sorry for the confusion.
