### ISSUE TITLE
about fine tune

### ISSUE THREAD

**Issue by yuanCnD** [Tencent/PocketFlow#13]
there is a question that i want to ask:
  in real application, for example like image binary classification,  there are tow method i can use with this scrips : 1 down pretrain model and compress it, then finetune from aleady compressed pretrain model to binary cls model. 2 down pretrain model and finetune from pretrain model to binary cls model, then compress binary cls model. which method can you suggest me to chose? of course , both method i can try to chose the better one , but i just want to ask for your opinion.

**Comment by jiaxiang-wu** [comment]
Hi, I suggest you try and evaluate both methods on your task. It is hard to tell which one is better, since it is closely related to what your task is, which model you are using, and which model compression method you are using.
