### ISSUE TITLE
Minor bug in weight sparsification learner

### ISSUE THREAD

**Issue by haolibai** [Tencent/PocketFlow#130]
**Describe the bug**
According to [To prune, or not to prune: exploring the efficacy of pruning for model compression](https://arxiv.org/abs/1710.01878), the mask should be updated based on the un-pruned weights. However in the code, the mask is updated based on the pruned weights.

**Screenshots**
![image](https://user-images.githubusercontent.com/24502378/49632885-48b60f80-fa32-11e8-98a4-eed9da713533.png)

**Comment by jiaxiang-wu** [comment]
Thanks for pointing it out. Both `mask_thres` and `mask` should be updated based on `var_bkup`, rather than `var` in the current implementation. We will fix it ASAP.

**Comment by jiaxiang-wu** [comment]
Resolved in PR #134.
