### ISSUE TITLE
How to export the compressed model to TensorFlow Lite when i use weight-sparse learner?

### ISSUE THREAD

**Issue by yupanpanwangrui** [Tencent/PocketFlow#133]
I use weight-sparse learner to compress resnet model on cifar10 dataset. It is normal. 

But I don't know how to export the compressed model to tflite model, using export_quant_tflite_model.py or export_chn_tflite_model.py?  I tried the two ways, but failed.  Can anyone help me?

**Comment by jiaxiang-wu** [comment]
Same as issue #125.
The compressed model generated by `WeightSparseLearner` does not support exporting to TensorFlow Lite, since sparse matrix multiplication is not supported by TensorFlow Lite, as far as I know. Sorry for the confusion.
