### ISSUE TITLE
Why performance does not improve after channel pruning

### ISSUE THREAD

**Issue by herbiezhao** [Tencent/PocketFlow#140]
I compress our model using channel pruning with pruning ratio 0.5.
But converted models perform as same as original model on Nvidia GPU.

**Comment by jiaxiang-wu** [comment]
Which model are you using for speed test, *.ckpt or *.pb?

**Comment by herbiezhao** [comment]
*.ckpt

**Comment by jiaxiang-wu** [comment]
We do not modify the graph architecture in the *.ckpt files. For GPU-based inference speed-up, you need to use the *.pb files, which removes all-zeros channels after channel pruning.
To generate a *.pb model file, you need to use `tools/conversion/convert_data_format.py` to convert a model from NHWC data format to NCHW data format (which runs faster) and then use `tools/conversion/export_chn_pruned_tflite_model.py` to export *.pb and *.tflite models from *.ckpt files. Use *.pb for GPU-based inference and *.tflite for CPU/ARM-based inference.

**Comment by herbiezhao** [comment]
I see！Thanks！
