### ISSUE TITLE
Which AutoML method is used in the current version of PocketFlow？

### ISSUE THREAD

**Issue by Maoquan232** [Tencent/PocketFlow#149]
Hi, you mentioned in Github that  Gaussian Processes (GP, Mockus, 1975), Tree-structured Parzen Estimator (TPE, Bergstra et al., 2013), and Deterministic Deep Policy Gradients (DDPG, Lillicrap et al., 2016) will be used for hyper-parameters optimization.

While it seems that the automl methods GP and TPE haven't been used in the current version, right?(Only RL-DDPG)
 Will you open the source code in recent days?

**Comment by jiaxiang-wu** [comment]
Yes, both GP and TPE are not included in the current repo. They are based on another project which is not released. We are planning to provide GP and TPE support within PocketFlow, but there is no clear timetable for this, since our current priority is to support object detection models.

**Comment by aakejiang** [comment]
"Deterministic Deep Policy Gradients" or "Deep Deterministic Policy Gradient" ?

**Comment by jiangke-sr** [comment]
@jiaxiang-wu How about now, are GP and TPE supported? Since there are still no implementations in "automl" module.
