### ISSUE TITLE
Compressed model file from Channel Pruning

### ISSUE THREAD

**Issue by dhingratul** [Tencent/PocketFlow#15]
Can you provide the optimized output from tf.Saver.save() from as the .pb file before the tflite conversion
`$ ./scripts/run_local.sh nets/resnet_at_ilsvrc12_run.py \
    --learner dis-chn-pruned`

**Comment by jiaxiang-wu** [comment]
Sorry, I do not fully understand your question. What do you mean by "optimized output from tf.Saver.save() from as the .pb file"?

**Comment by dhingratul** [comment]
I am talking about the output from "Train the Compressed Model" in the tutorial,  https://pocketflow.github.io/tutorial/. I am assuming as the next step is to export it as a TFLITE file, the output from the above step is a .pb file, I am looking for that file. I see you benchmarked your optimizations for Mobile Device, i am looking to do the same for the GPU, for which i need the .pb file before you generate the tflite file.

**Comment by jiaxiang-wu** [comment]
`tools/conversion/export_pb_tflite_models.py` generates both *.pb and *.tflite model files, located in the same directory. Can you find them in the directory specified by `--model_dir`?

**Comment by dhingratul** [comment]
The imagenet download is super slow, the last time I did that it took almost 3-4 days to complete. I just want to skip that and get the .pb file directly from that tutorial if possible.

**Comment by jiaxiang-wu** [comment]
Sorry, `ChannelPrunedLearner` requires the imagenet data set to complete its training process. Maybe you can try using smaller data sets, like CIFAR-10? Some modification will be required:
1. `nets/resnet_at_ilsvrc12_run.py` -> `nets/resnet_at_cifar10_run.py`
2. In `ImageClassifierFloatResNet.java`, change the image size and label file.

**Comment by dhingratul** [comment]
Yes, i understand, i was hoping that you have that you make the optimized model(after pruning) available so that i can do some benchmarks to make sure the results in terms of gains is reproducible on my machine.

**Comment by jiaxiang-wu** [comment]
Okay, we will release pre-trained compressed models for some selected pruning ratio in the next few weeks.

**Comment by jiaxiang-wu** [comment]
Enhancement required: release a few pre-trained compressed models for benchmark test.

**Comment by jiaxiang-wu** [comment]
@dhingratul We will, but it may take some time.
