### ISSUE TITLE
Parameters for RL-based WeightSparseLearner on MobileNets

### ISSUE THREAD

**Issue by d-jax** [Tencent/PocketFlow#150]
Hello PocketFlow team, 

What are the parameters for reproducing the compressed MobileNets using weight sparsification as reported by the PocketFlow paper? Thank you.

**Comment by d-jax** [comment]
@jiaxiang-wu This is super helpful. Thanks for sharing. How transferrable do you think these params are from MobileNet V1 to, say MobileNet V2, Inception, etc.? It'd be great to learn the optimal training parameters for more popular models.

**Comment by jiaxiang-wu** [comment]
These hyper-parameters work well on both ResNet and MobileNet-v1. I think they can be generalized to MobileNet-v2 or Inception models. The change for the last four hyper-parameters is mainly due to different data sets (CIFAR-10 vs. ILSVRC-12), instead of different models.

**Comment by d-jax** [comment]
Thanks again. One more question: is there a sparsity/performance gap between the 'heurist' and 'optimal' protocols for weight sparsification? I assume the 'heurist' protocol follows the "To prune, or not to prune" paper.

**Comment by jiaxiang-wu** [comment]
The "heurist" protocol does not correspond to the "To prune, or not to prune" paper. We think the core idea of that paper is to use a gradually increasing pruning ratio to boost the sparsity-constrained training, and this is implemented in `WeightSparseLearner`, regardless whatever protocol you are using. The "heurist" protocol actually follows the assumption that layers with more parameters should have larger redundancy and can be assigned with a larger pruning ratio.
