### ISSUE TITLE
I purning my own network by DCP，but it ran into a endless loop after a warning

### ISSUE THREAD

**Issue by sunzhe09** [Tencent/PocketFlow#151]
here is my log：
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5859
INFO:tensorflow:adding channel #34 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5820
INFO:tensorflow:adding channel #147 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5781
INFO:tensorflow:adding channel #239 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5742
INFO:tensorflow:adding channel #163 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5703
INFO:tensorflow:adding channel #65 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5664
INFO:tensorflow:adding channel #161 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5625
INFO:tensorflow:adding channel #5 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5586
INFO:tensorflow:adding channel #191 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
/data/raid/PocketFlow_test/learners/discr_channel_pruning/learner.py:498: RuntimeWarning: invalid value encountered in multiply
  idx_chn_input = np.argmax(grad_norm * grad_norm_mask)
INFO:tensorflow:adding channel #135 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547
INFO:tensorflow:adding channel #0 to the non-pruned set
INFO:tensorflow:layer #12: prune_ratio = 0.5547

I don‘t know what‘s  wrong ，please help me。3q！

**Comment by jiaxiang-wu** [comment]
PR #147 should have already solved this issue. Are you using the latest code?

**Comment by sunzhe09** [comment]
I have check my code ，it‘s  not  the  latest

**Comment by jiaxiang-wu** [comment]
So can you re-run with the latest code?

**Comment by sunzhe09** [comment]
yes ，but i have another question， when I run into horovod docker ，it crashed with ./scripts/run_docker.sh: line 45: nvidia-docker: command not found

**Comment by jiaxiang-wu** [comment]
When you enter the docker environment, you should start the program using `bash main.sh`, instead of calling `./scripts/run_docker.sh` again.

**Comment by sunzhe09** [comment]
1.docker pull the latest images
2.clone my own container
3.nvidia-docker exec -it sz_horovod bash  &&cd Pocketfllow

**Comment by jiaxiang-wu** [comment]
You need to start the docker environment using `./scripts/run_docker.sh`, and when you entered the docker environment, use `bash main.sh` to start the program.

**Comment by sunzhe09** [comment]
so , I should ran the images in nvidia-docker?

**Comment by jiaxiang-wu** [comment]
Sorry, I did not understand your question.

**Comment by sunzhe09** [comment]
well, I ran the command as you said above ,
Traceback (most recent call last):
  File "utils/get_idle_gpus.py", line 40, in <module>
    for gpu in gpu_smi_output.split(sep='\n')[:-1]:
TypeError: split() takes no keyword arguments
nvidia-docker | 2018/12/18 16:47:03 Error: Error response from daemon: Get https://docker.oa.com/v1/_ping: remote error: tls: alert(112)

**Comment by jiaxiang-wu** [comment]
Which Python version are you using, 2.x or 3.x?

**Comment by sunzhe09** [comment]
2.7 ...

**Comment by jiaxiang-wu** [comment]
Can you using Python 3.x as we suggested [here](https://pocketflow.github.io/installation/)? Our code is developed and tested under Python 3.6.

**Comment by sunzhe09** [comment]
3q，there is another problem：
nvidia-docker | 2018/12/18 17:41:21 Error: Error response from daemon: Get https://docker.oa.com/v1/_ping: remote error: tls: alert(112)

**Comment by jiaxiang-wu** [comment]
Can you give the execution command and full log for your problem? It is a little bit difficult to understand what went wrong based on the current information.

**Comment by sunzhe09** [comment]
I had solve this problem ,now,I have another question, if I want to train or purning my own model how to put my dataset and pretrain model into the horovod docker,just as local model?

**Comment by jiaxiang-wu** [comment]
You can mount directories into the docker environment using the "-v <local_path>:<docker_path>" option. See `scripts/run_docker.sh` for details.

**Comment by sunzhe09** [comment]
OK,THX!!

**Comment by sunzhe09** [comment]
I miss the pretrain model
