### ISSUE TITLE
Can I quantize only some layers of the entire model?

### ISSUE THREAD

**Issue by iamhankai** [Tencent/PocketFlow#153]
I donot want to quantize the entire model, so can I quantize only some layers or some parameters of the entire model?
For example, y=xw+b, only quantize w and keep b unchanged.

**Comment by jiaxiang-wu** [comment]
Partially quantized models cannot be accelerated via TF-Lite and will not have actual speed-up.

**Comment by iamhankai** [comment]
Actually, I have quantized some parameters by myself, so I donot need further quantize them.

**Comment by jiaxiang-wu** [comment]
TensorFlow's quantization-aware training APIs operate on the whole-graph level. You can manually record and update the quantization information by yourself, but if you still want to deploy using TF-Lite, you need to find out how to convert your quantization information into TensorFlow's.
