### ISSUE TITLE
Is there a plan for generalizing pockeflow api to detection models since current model helper can't be applied to detection task

### ISSUE THREAD

**Issue by xiaomr** [Tencent/PocketFlow#164]

**Comment by jiaxiang-wu** [comment]
We are adding support for SSD models for object detection and should be able to release it soon.

**Comment by xiaomr** [comment]
Is it based on current model helper and learner design or it will add a new model helper class and detect learner?

**Comment by jiaxiang-wu** [comment]
In the current implementation, we introduce a new model helper. Some minor changes to the existing learners may be required, but not a completely new learner.

**Comment by xiaomr** [comment]
I tried some experiment in detection task by making a new detect learner but it seems a little hack。 Do you mean that  different tasks will use different  model helper but share the same learner ,  and use conditional judgment (classification or detection) to determine how to use  model helper api accordingly in the learner? Looking forward to the release,  does it have time plan?

**Comment by jiaxiang-wu** [comment]
For classification and detection, we use different model helpers but the same learner. No clear time plan for now, but we will release it as soon as it is ready.

**Comment by brisker** [comment]
@jiaxiang-wu 
what about this issue I mentioned here
https://github.com/Tencent/PocketFlow/issues/115#issuecomment-449797231

**Comment by jiaxiang-wu** [comment]
@brisker 
Please do not discuss irrelevant issues here. I have replied to you in #115.
