### ISSUE TITLE
My server crash,how can I pruning with the old ckpt file?I don't want to train from strach

### ISSUE THREAD

**Issue by sunzhe09** [Tencent/PocketFlow#167]
Besides,I have met another problem:
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_55_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_53_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_50_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_51_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_49_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_47_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_48_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_44_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_45_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_43_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_41_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_42_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_40_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_38_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_39_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_37_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_35_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_36_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_34_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_31_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_32_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_30_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_28_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_29_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_27_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_2_FusedBatchNorm_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_2_FusedBatchNorm_grad_tuple_control_dependency_2_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_1_FusedBatchNorm_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_FusedBatchNorm_grad_tuple_control_dependency_2_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_1_FusedBatchNorm_grad_tuple_control_dependency_2_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_batch_normalization_FusedBatchNorm_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_25_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_26_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_23_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_20_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_21_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_19_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_46_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_17_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_18_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_16_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_14_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_15_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_13_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_11_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_12_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_10_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_8_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_7_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_5_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_6_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_4_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_9_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_2_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_3_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_AddN_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_2_MatMul_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_1_MatMul_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_MatMul_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_1_BiasAdd_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_2_BiasAdd_grad_tuple_control_dependency_1_0 [missing ranks: 0]
pruned_model/DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_pruned_model_gradients_40_pruned_model_dense_BiasAdd_grad_tuple_control_dependency_1_0 [missing ranks: 0]

**Comment by jiaxiang-wu** [comment]
1. `ChannelPrunedLearner` does not support resuming from a previous run.
2. Is "[missing ranks: 0]" a warning message or error? If the former, it is possible that the worker with rank 0 is evaluating the model, while other workers are waiting for it.
