### ISSUE TITLE
How to use a keras model in pockerflow

### ISSUE THREAD

**Issue by hzhyhx1117** [Tencent/PocketFlow#168]
I would like to make a keras model be suitable for pocketflow. 
When I define my owner ModelHelper, should I code the function forward_fn and calc_loss in tf method?
Any suggestion for me about to use keras' Model and compile to complete such things? Thanks

**Comment by hzhyhx1117** [comment]
@jiaxiang-wu 
Since tf has APIs like tf.keras, if I change my code into such methods ,can learners recoognize them ?

**Comment by jiaxiang-wu** [comment]
I am not sure whether learners can recognize the keras code. You may need to try it out.

**Comment by hzhyhx1117** [comment]
Thanks, do you have any plans to support keras model in the future?

**Comment by jiaxiang-wu** [comment]
Not in the near future. Currently, our top priority is to support detection/segmentation models for CV and RNN/LSTM models for ASR/NLP.

**Comment by hzhyhx1117** [comment]
Ok, thanks for your info. Closed the issue
