### ISSUE TITLE
Question about transforming the ckpt model to pb model

### ISSUE THREAD

**Issue by deargqy** [Tencent/PocketFlow#179]
Hello,

First of all, thanks a lot for the effort you made.

May I ask if I can transform the quantized model which is .ckpt format to .pb format? I tried several methods but they all failed... Meanwhile, I noticed in your documentation that the performance of 8-bit quantized models is even better than the original ones. May I know how you get this model(I mean the command you used).

**Comment by deargqy** [comment]
Thanks a lot for your reply.

I tried the command you recommended, and everything worked as expected. However, I found another problem when using

I tried the learners of uniform and non_uniform quantization, I found the size of the final models is about 49M(which the original is 33M). I know it's because of these models saved both the original and new weights. Therefore the method in tools/conversion/export_quant_tflite_model.py cannot generate *.pb & *.tflite models. May I ask how can I convert these saved files(which are checkpoint file, .data file, .meta file and .index file) to a pb and tflite model.

BW

**Comment by jiaxiang-wu** [comment]
`tools/conversion/export_quant_tflite_model.py` only supports compressed models generated by `UniformQuantTFLearner`, which uses TensorFlow's quantization-aware training APIs during training. The other two learners, `UniformQuantLearner` and `NonUniformQuantLearner`, are for experimental usage to test how well the RL agent can optimize the layer-wise hyper-parameters.
