### ISSUE TITLE
关于量化后的模型输入

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/PocketFlow#181]
hi，
我用PocketFlow 量化了一个自己训练的模型，用的命令如下
sh ./scripts/run_local.sh nets/convnet_at_sr_run.py \
--learner=uniform \
--uql_weight_bits=8 \
--uql_activation_bits=8 \
--uql_use_buckets=True \
--uql_bucket_type=channel

相应的更改了learner等代码，但freeze之后出来的模型有3个 Placeholder
model/a_bit_list (Placeholder): []
model/w_bit_list (Placeholder): []
net_input (Placeholder): []

请问在测试的时候 model/a_bit_list (Placeholder): [] 和 model/w_bit_list (Placeholder): []  这两个应该给什么输入？

**Comment by haolibai** [comment]
如果训练的时候activaiton和weight都是8 bit，那么测试的时候也保持一致，即 model/a_bit_list (Placeholder): [] 和 model/w_bit_list (Placeholder): []为 [8] * num_of_activations和 [8] * num_of_layers

**Comment by huanyingjun** [comment]
thanks
