### ISSUE TITLE
Does support prune, sparse, quantize stage-wisely for one model?

### ISSUE THREAD

**Issue by ysh329** [Tencent/PocketFlow#182]
Hi, all,

I found some [test cases in our docs](https://pocketflow.github.io/test_cases/) but they're all using one method, such as punning, weight sparsification, weight quantization. 

Each test case uses one compression method but does support stage-wise do compression(punning, weight sparsification, weight quantization) for one model?

----

We found if using one compression method such as pruning, many pieces file about mode left. Can we using left model files as input of next compression stage? If yes, have any cases or detailed information?

Thanks in advance.

**Comment by jiaxiang-wu** [comment]
For now, no. Each learner will introduce some extra TensorFlow OPs into the graph, and it is hard to remove these OPs in the ckpt files (but for *.pb & *.tflite models, these OPs can be removed). This will cause trouble for the subsequent learner to be used. A possible approach for combining channel-pruning and other learners (*e.g.* weight sparsification, quantization) is to manually create a new model with fewer channels, feed in model weights in the channel-pruned model, and use it for other learners.

**Comment by ysh329** [comment]
Thanks. 🙇
