### ISSUE TITLE
Have any demo to compress detection model

### ISSUE THREAD

**Issue by ysh329** [Tencent/PocketFlow#184]
Hi all,

Have any demo to prune detection model, I found many test cases in docs, all of them are to compress classification model.

If I need to compress a our-self special rcnn or ssd model (of course, trained on our own data set), how to modify test case to adapt our model to compress or have any case to compress detection model?

Thanks in advance.

**Comment by jiaxiang-wu** [comment]
We are testing channel pruning and uniform quantization for the SSD model. As soon as we are ready, corresponding code and detailed documentation will be provided.

**Comment by ysh329** [comment]
Thanks 👍
