### ISSUE TITLE
A question about channel  pruning

### ISSUE THREAD

**Issue by to-be-snail** [Tencent/PocketFlow#188]
I have a question...After pruning some channels,the finetune process will train the pruned channel or not?Thanks for some replies.

**Comment by jiaxiang-wu** [comment]
The pruned channels will remaining all zeros (or kept unchanged, depending on which channel pruning learner you are using), and the preserved channels will be training.

**Comment by to-be-snail** [comment]
> The pruned channels will remaining all zeros (or kept unchanged, depending on which channel pruning learner you are using), and the preserved channels will be training.

thanks for your reply.But another question is that,the original model flops is 22482944.0,after first prune the model flops is 2081250.After that,I tried second prune on the pruned model,but the log shows the model flops is 22482944.0 before second prune.

**Comment by jiaxiang-wu** [comment]
The pruned channels are not removed during the training process. We only mask them out so that those weights are kept unchanged or reset to zeros. They are removed when exporting *.pb & *.tflite models.

**Comment by to-be-snail** [comment]
> The pruned channels are not removed during the training process. We only mask them out so that those weights are kept unchanged or reset to zeros. They are removed when exporting *.pb & *.tflite models.

I get it.thank you!

**Comment by jiaxiang-wu** [comment]
You're welcome. ^_^
