### ISSUE TITLE
The structure of model in __build_pruned_evaluate_model

### ISSUE THREAD

**Issue by as754770178** [Tencent/PocketFlow#195]
the code show as below 
```
  self.__finetune_pruned_model(path=FLAGS.cp_channel_pruned_path)

  def __finetune_pruned_model(self, path=None, finetune=False):
    if path is None:
      path = FLAGS.cp_channel_pruned_path
    start = timer()
    tf.logging.info('build pruned evaluating model')
    self.__build_pruned_evaluate_model(path)
    tf.logging.info('build pruned training model')
    self.__build_pruned_train_model(path, finetune=finetune)
    tf.logging.info('training pruned model')
    self.__train_pruned_model(finetune=finetune)
    tf.logging.info('fintuning time cost: {}s'.format(timer() - start))

  def __build_pruned_evaluate_model(self, path=None):
    ''' build a evaluation model from pruned model '''
    # early break for non-primary workers
    if not self.__is_primary_worker():
      return

    if path is None:
      path = FLAGS.save_path

    if not tf.train.checkpoint_exists(path):
      return

    with tf.Graph().as_default():
      config = tf.ConfigProto()
      config.gpu_options.visible_device_list = str(# pylint: disable=no-member
        mgw.local_rank() if FLAGS.enbl_multi_gpu else 0)
      self.sess_eval = tf.Session(config=config)
      self.saver_eval = tf.train.import_meta_graph(path + '.meta')
      self.saver_eval.restore(self.sess_eval, path)
  ......
```

I want to know the graph in eval is same in train?  because the model in `cp_channel_pruned_path` is saved by `self.saver_train.save(self.sess_train, FLAGS.cp_original_path)`.

**Comment by jiaxiang-wu** [comment]
The training and evaluation graph should be the same (apart from some training-only operations). The variables defined in the evaluation graph can be found in the training graph with the same name; otherwise, the saver in the evaluation graph won't be able to restore the model.

**Comment by as754770178** [comment]
I know the variables is same in the evaluation graph and the training graph, but I think that the structure of model is different. The code `self.saver_eval = tf.train.import_meta_graph(path + '.meta')`, import the training graph as the evaluation graph. This is right for all kind of model?

`otherwise, the saver in the evaluation graph won't be able to restore the model.` The structure of model and the variables are introduced from the same `ckpt` file, so the saver in the evaluation graph must be able to restore the model.

**Comment by jiaxiang-wu** [comment]
This should be right for all kind of models. If you have found a case that the current implementation fails, please feel free to report it to us.

**Comment by as754770178** [comment]
This mean that `forward_eval` in `ModelHelper` class is useless when use `ChannelPrunedLearner`?

**Comment by jiaxiang-wu** [comment]
If `enbl_dst` is not enabled, yes, `forward_eval` in the `ModelHelper` class is not used. Otherwise, `DistillationHelper` will still use `forward_eval` in the `ModelHelper` class here:
https://github.com/Tencent/PocketFlow/blob/master/learners/distillation_helper.py#L76

**Comment by jiaxiang-wu** [comment]
Based on my understanding, the BN layer in the training graph will only have some extra training-related operations (to update the moving average statistics), comparing with the BN layer in the evaluation graph. For the computation procedure in the forward pass, these two should be the same.

**Comment by as754770178** [comment]
OK, thanks

**Comment by jiaxiang-wu** [comment]
Thanks for your suggestion.
