### ISSUE TITLE
怎么将量化后的模型转成tflite ?

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/PocketFlow#198]
hi
我用UniformQuantLearner量化出了模型
sh ./scripts/run_local.sh nets/convnet_at_sr_run.py \
--learner=uniform \
--uql_weight_bits=8 \
--uql_activation_bits=8 \
--uql_use_buckets=True \
--uql_bucket_type=channel

然后将模型freeze好成pb之后，怎么转成uint8的tflite呢？下面的命令是给UniformQuantTFLearner 用的，
是否同样适用于UniformQuantLearner ？
tflite_convert \
  --graph_def_file=/home/ming/share/model.pb \
  --output_file=/home/ming/share/model.tflite \
  --inference_type=QUANTIZED_UINT8 \
  --input_arrays=net_input \
  --input_shape=1,360,640,3 \
  --output_arrays=model/add  \
  --allow_custom_ops \
  --mean_values 128 \
  --std_dev_values 127 \
  --default_ranges_min 0 \
  --default_ranges_max 6

**Comment by jiaxiang-wu** [comment]
Only `UniformQuantTFLearner` supports exporting the uniform quantized model to *.pb & *.tflite files. `UniformQuantLearner` does not support this, since it is not based on TensorFlow's quantization-aware training APIs.

**Comment by huanyingjun** [comment]
> Only `UniformQuantTFLearner` supports exporting the uniform quantized model to *.pb & *.tflite files. `UniformQuantLearner` does not support this, since it is not based on TensorFlow's quantization-aware training APIs.


那有什么工具可以将UniformQuantLearner 转成tflite吗？ 
或者要用 UniformQuantLearner 的模型，应该怎么在手机设备端运行呢？

**Comment by jiaxiang-wu** [comment]
Please use `UniformQuantTFLearner` to enable TF-lite based inference.

**Comment by huanyingjun** [comment]
thanks
