### ISSUE TITLE
Can you create a module to take out the specification feature maps so that we can know what is the output of the kernel

### ISSUE THREAD

**Issue by jiuyecao** [Tencent/PocketFlow#202]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jiaxiang-wu** [comment]
You mean the shape or the value of certain feature maps?

**Comment by jiuyecao** [comment]
> You mean the shape or the value of certain feature maps?

the value of feature maps

**Comment by jiaxiang-wu** [comment]
How would you like to specify which feature map to be inspected? This may differ in different models.

**Comment by jiaxiang-wu** [comment]
@jiuyecao Any updates/suggestions?
