### ISSUE TITLE
How can i continue training the model that aborted before? I put the relative ckpt into the ./models and set learner to full-prec but it seems like the full-prec doesn't load the model, so how can i continue traning a model or training a self-defined model?

### ISSUE THREAD

**Issue by jiuyecao** [Tencent/PocketFlow#204]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with PocketFlow, or support for problems that are not verified bugs in PocketFlow, please go to [StackOverflow](https://stackoverflow.com).

For high-level discussions about TensorFlow, please post to [discuss group](https://groups.google.com/forum/#!forum/pocketflow).

**Comment by jiaxiang-wu** [comment]
We do not support this feature for the moment.
