### ISSUE TITLE
why weight_sparsification can reduce flops

### ISSUE THREAD

**Issue by smalltingting** [Tencent/PocketFlow#217]
hello，may I ask you two questions?

why weight_sparsification can reduce flops？
 
and will the size of model reduce after weight_sparsification ？

**Comment by yuanyuanli85** [comment]
If you are using standard tensorflow or hardware, they can't take the advantage of sparse model to reduce model size and flops. But, will give chance to particular hardware or library to skip the computing with zero weights. let's say i have a GPU with is designed for sparse computing, then the sparse model will run much faster on that than standard GPU.  I think there will be more and more platform/hardware can support that in feature.

**Comment by jiaxiang-wu** [comment]
Thanks for the detailed explanation from @yuanyuanli85 . Some extra information:

1. Theoretically, FLOPs can be reduced, if you can take advantage of the sparsity during computation. However, most inference engine do not have highly-optimized implementation for sparse matrix/tensor operations, and sparse matrices are often converted into dense ones so the FLOPs does not change.
2. In *.ckpt models, zero-valued weights are still stored, hence there won't be any changes in the model size.

**Comment by smalltingting** [comment]
> If you are using standard tensorflow or hardware, they can't take the advantage of sparse model to reduce model size and flops. But, will give chance to particular hardware or library to skip the computing with zero weights. let's say i have a GPU with is designed for sparse computing, then the sparse model will run much faster on that than standard GPU. I think there will be more and more platform/hardware can support that in feature.



> If you are using standard tensorflow or hardware, they can't take the advantage of sparse model to reduce model size and flops. But, will give chance to particular hardware or library to skip the computing with zero weights. let's say i have a GPU with is designed for sparse computing, then the sparse model will run much faster on that than standard GPU. I think there will be more and more platform/hardware can support that in feature.

Thanks a lot. I  

> If you are using standard tensorflow or hardware, they can't take the advantage of sparse model to reduce model size and flops. But, will give chance to particular hardware or library to skip the computing with zero weights. let's say i have a GPU with is designed for sparse computing, then the sparse model will run much faster on that than standard GPU. I think there will be more and more platform/hardware can support that in feature.

Thanks a lot.

**Comment by smalltingting** [comment]
> If you are using standard tensorflow or hardware, they can't take the advantage of sparse model to reduce model size and flops. But, will give chance to particular hardware or library to skip the computing with zero weights. let's say i have a GPU with is designed for sparse computing, then the sparse model will run much faster on that than standard GPU. I think there will be more and more platform/hardware can support that in feature.

Thanks a lot.
