### ISSUE TITLE
The compression model deployed on the server does not perform well

### ISSUE THREAD

**Issue by sysuxiaoming** [Tencent/PocketFlow#221]
Hi all，our problem is how to deploy the model compressed by PocketFlow on the server to get better performance(we mainly concerned about GPU memory reduction and inference acceleration). From https://pocketflow.github.io/performance we only get the speed-up info of quantized model, which are TensorFlow Lite format for deployment on mobile devices. However TensorFlow Lite format models are not suitable for deployment on the server, so we try to find out the performance of the compressed pb format model (or other model format that can be deployed on the server). We did a small experiment, but the result was not normal. Details as follow:

We use the code(tools/conversion/export_pb_tflite_models.py) to get 11 channel-pruned models, and their prune-ratio are 0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99. The original model we used is resnet20_at_cifar10. Then we use the code(tools/benchmark/calc_inference_time.py) to get performance of compressed models and the batch-size are 1, 10, 100, 1000.

Inference time result as follow:
![image](https://user-images.githubusercontent.com/8336802/52038041-e2e68f80-256b-11e9-8fa3-df7c1663a2d1.png)

We get the GPU memory usage info from nvidia-smi, the result as follow:
![image](https://user-images.githubusercontent.com/8336802/52038067-ff82c780-256b-11e9-9776-b75b4750c5e7.png)

The results show that even with 90%  pruning rate the performance improvement is very small. Is this normal?

Can you provide more inference acceleration or memory reduction statistics for different model deployed on the server with different compression algorithm?

In addition, the current version does not provide quantification for the pb model. Will you later provide quantification for models deployed on the server?

**Comment by jiaxiang-wu** [comment]
Sorry for the late reply.
In the current version, the actual speed-up of channel pruned models is not very ideal, since there are still some redundant computation in *.pb models, even after graph transformation. We are considering completely rewrite the graph (conv layer and corresponding input/output layers) to achieve higher speed-up. Besides, you may try to evaluate channel pruning's acceleration effect on ResNet @ ILSVRC-12.
