### ISSUE TITLE
QQ group password incorrect?

### ISSUE THREAD

**Issue by EuphorbiaHirta** [Tencent/PocketFlow#225]
Hi All!
I'm a postgraduate student and I am very interested in model compression technology.
When I try joining the QQ group, the password required confuses me.
I've tried '腾讯','腾讯公司','Tencent','腾讯计算机系统有限公司' and other possible answers but all got wrong. Am I not clever enough?
I'll be grateful if you can tell me the right answer for the question or invite me directly(My QQ number is 360960956), or if I don't meet the conditions for joining the group, please let me know.

**Comment by jiaxiang-wu** [comment]
"腾讯" does not work? Make sure there is no leading / trailing white-spaces.

**Comment by jiaxiang-wu** [comment]
Already invited.

**Comment by ginger0106** [comment]
same problem...

**Comment by ginger0106** [comment]
my qq number is 178171378, thanks

**Comment by jiaxiang-wu** [comment]
@ginger0106 Could you try again? If still does not work, please report here and I will invite you in.
