### ISSUE TITLE
speed up question about channel pruning

### ISSUE THREAD

**Issue by to-be-snail** [Tencent/PocketFlow#227]
Hello,I have a question is that if channel pruning can reduce the inference time of model.I made some tests and observed that the inference time didn't reduce after pruning.

**Comment by to-be-snail** [comment]
Anyone can help me?

**Comment by jiaxiang-wu** [comment]
Which network are you compressing? Also, issue #214 seems related to your question.

**Comment by to-be-snail** [comment]
> Which network are you compressing? Also, issue #214 seems related to your question.

mobilenet v1

**Comment by jiaxiang-wu** [comment]
The actual speed-up depends on the graph transformation method used for exporting *.pb and *.tflite models. Current implementation is the most efficient one, which leads to the gap between theoretical and realistic speed-up. Please refer to issue #214 for more detailed discussion and explanation. @to-be-snail

**Comment by to-be-snail** [comment]
> The actual speed-up depends on the graph transformation method used for exporting *.pb and *.tflite models. Current implementation is the most efficient one, which leads to the gap between theoretical and realistic speed-up. Please refer to issue #214 for more detailed discussion and explanation. @to-be-snail

OK,get it,thank you!

**Comment by to-be-snail** [comment]
> The actual speed-up depends on the graph transformation method used for exporting *.pb and *.tflite models. Current implementation is the most efficient one, which leads to the gap between theoretical and realistic speed-up. Please refer to issue #214 for more detailed discussion and explanation. @to-be-snail

OK,get it,thank you!

> > The actual speed-up depends on the graph transformation method used for exporting *.pb and *.tflite models. Current implementation is the most efficient one, which leads to the gap between theoretical and realistic speed-up. Please refer to issue #214 for more detailed discussion and explanation. @to-be-snail
> 
> OK,get it,thank you!

I have read the codes in export_chn_pruned_tflite_model.py and have generated the original_model.pb and transformed_model.pb. I have found the difference between the two models is small,the original model is 12000+kb and the transformed model is 11000+kb,and both of their inference time is 5+ms.

**Comment by to-be-snail** [comment]
> The actual speed-up depends on the graph transformation method used for exporting *.pb and *.tflite models. Current implementation is the most efficient one, which leads to the gap between theoretical and realistic speed-up. Please refer to issue #214 for more detailed discussion and explanation. @to-be-snail

I have read the codes in export_chn_pruned_tflite_model.py and have generated the original_model.pb and transformed_model.pb. I have found the difference between the two models is small,the original model is 12000+kb and the transformed model is 11000+kb,and both of their inference time is 5+ms.
