### ISSUE TITLE
使用UniformQuantLearner训练后的模型转换TFLITE预测结果错误

### ISSUE THREAD

**Issue by wanghao0525** [Tencent/PocketFlow#231]
UniformQuantLearner量化命令：
./scripts/run_seven.sh nets/convnet_at_mine_run.py \
--learner uniform-tf \
--nb_epochs_rat 0.2

TFLITE转换命令：
python tools/conversion/export_quant_tflite_model.py \
--model_dir ./models_uqtf_eval \ 
--enbl_post_quant

TFLITE转换参数：
  arg_list = [
    '--graph_def_file ' + file_path_pb,
    '--output_file ' + file_path_tflite,
    '--input_arrays ' + net['input_name'],
    '--output_arrays ' + net['output_name']]
  if not enbl_quant:
    arg_list += ['--inference_type FLOAT']
  else:
    arg_list += [
      '--inference_type QUANTIZED_UINT8',
      '--mean_values 0',
      '--std_dev_values 1']
    if FLAGS.enbl_post_quant:
      arg_list += [
        '--default_ranges_min 0',
        '--default_ranges_max 6']
  cmd_str = ' '.join(['tflite_convert'] + arg_list)

转换后的model_original.pb和model_original.tflite预测结果正确，model_quantized.tflite预测结果错误，训练和预测输入的都是原图，均未做归一化。

**Comment by ferriswym** [comment]
遇到了同样的问题，请问找到解决方案吗？
