### ISSUE TITLE
Is there anyone know how many iters will run in the finetune process after pruning?

### ISSUE THREAD

**Issue by to-be-snail** [Tencent/PocketFlow#235]
MobileNet V1 at ilsvrc12, I'm not sure if the time is enough for me to complete the experiment.

**Comment by to-be-snail** [comment]
I have ran 220000+ iters..

**Comment by to-be-snail** [comment]
I have ran 22W iters..

**Comment by jiaxiang-wu** [comment]
For MobileNet-v1, 100 epochs will be used for fine-tuning. You can reduce it by lowering `FLAGS.nb_epochs_rat`. It depends on the batch size to determine how many iterations will be used.
```plain
nb_iterations = nb_training_samples * nb_epochs * nb_epochs_rat / batch_size
```
For ILSVRC-12, `nb_training_samples` equals 1281167 and `nb_epochs` equals 100. The default value of `nb_epochs_rat` is 1.0.

**Comment by to-be-snail** [comment]
> For MobileNet-v1, 100 epochs will be used for fine-tuning. You can reduce it by lowering FLAGS.nb_epochs_rat. It depends on the batch size to determine how many iterations will be used.
> nb_iterations = nb_training_samples * nb_epochs * nb_epochs_rat / batch_size
> 
> For ILSVRC-12, nb_training_samples equals 1281167 and nb_epochs equals 100. The default value of nb_epochs_rat is 1.0.

Thanks for your reply,I just saw.
