### ISSUE TITLE
It seems that distillation didn't work.

### ISSUE THREAD

**Issue by to-be-snail** [Tencent/PocketFlow#237]
As the document mentioned,Distilling is an effective approach to improve the final accuracy of compressed model with PocketFlow in most situations of classification.So I compressed MobileNet V1 with prune ratio equals to 0.9,but the results showed that the test accuracy with dst is lower than the test accuracy without dst,I'm confused.Below is the results,the first is the log with dst,the second is another one.
![image](https://user-images.githubusercontent.com/22833087/53214590-18bcf680-3688-11e9-97c2-a46cd759a05b.png)

![image](https://user-images.githubusercontent.com/22833087/53214608-2a9e9980-3688-11e9-8173-6a4921100219.png)

**Comment by jiaxiang-wu** [comment]
You may try to adjust the following two hyper-parameters' values:
``` Python
tf.app.flags.DEFINE_float('loss_w_dst', 4.0, 'distillation loss\'s multiplier')
tf.app.flags.DEFINE_float('tempr_dst', 4.0, 'temperature in the distillation loss')
```
