### ISSUE TITLE
no requirements.txt file to help user install the necessary packages

### ISSUE THREAD

**Issue by EricDoug** [Tencent/PocketFlow#24]
When I running the command with the command **./scripts/run_local.sh nets/resnet_at_cifar10_run.py** in the installation documentation, but I found there are too many package shoud to install for run the demo. I wonder if it possible to add a requirements.txt file to call user intall the basic package for running the demo.

**Comment by jiaxiang-wu** [comment]
Enhancement required: add `requirements.txt` to list all dependencies.

**Comment by psyyz10** [comment]
Resolved in [PR#33](https://github.com/Tencent/PocketFlow/pull/33)
