### ISSUE TITLE
i can't get the horovod images  using the cmd 'docker pull uber/horovod' which provided by tutorial,how can i get the docker enviroment?  

### ISSUE THREAD

**Issue by MaxwellHan** [Tencent/PocketFlow#25]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with PocketFlow, or support for problems that are not verified bugs in PocketFlow, please go to [StackOverflow](https://stackoverflow.com).

For high-level discussions about TensorFlow, please post to [discuss group](https://groups.google.com/forum/#!forum/pocketflow).

**Comment by jiaxiang-wu** [comment]
Hi, can you post the error message?

**Comment by herbiezhao** [comment]
try "docker pull uber/horovod:0.14.1-tf1.10.0-torch0.4.0-py3.5"

**Comment by MaxwellHan** [comment]
> Hi, can you post the error message?
看了教程，我做了以下步骤的操作：
step1. path.conf中指定了cifar数据集的地址
step2. 我用 docker pull uber/horovod:0.15.1-tf1.11.0-torch0.4.1-py3.5  pull下了镜像
step3. 修改scripts/run_docker.sh 文件，把执行nvidia-docker的镜像名从 
           docker.oa.com/g_tfplus/horovod:python3.5  改为  uber/horovod:0.15.1-tf1.11.0-torch0.4.1-py3.5
step4. 执行./scripts/run_docker.sh  nets/resnet_at_cifar10_run.py，进入到了容器的bash命令中。但是既没有调用到gpu也没有运算，请问这样操作有什么问题，或者下一步应该做什么？

**Comment by jiaxiang-wu** [comment]
After entering the docker environment, use the following command to start the program:
``` bash
$ bash main.sh
```

P.S.: Please use English for future discussion, if possible.

**Comment by MaxwellHan** [comment]
> After entering the docker environment, use the following command to start the program:
> 
> ```shell
> $ bash main.sh
> ```
> 
> P.S.: Please use English for future discussion, if possible.

when i get into the docker eviroment and run "./main.sh" ,i got 
"Could not find a version that satisfies the requirement docopt" 
"Could not find a version that satisfies the requirement hdfs "
......
"Could not find a version that satisfies the requirement pandas" .et
,which means python doesn't have those modules.
Is the docker image "uber/horovod:0.15.1-tf1.11.0-torch0.4.1-py3.5" a wrong image?

My docker is in an internal network enviroment，which mean i can't connect the internet in the docker container, how do i fix this?

**Comment by xieydd** [comment]
I have veen tested in k8s , and use horovod ,it`s ok.
