### ISSUE TITLE
how i use docker mode or seven mode to train using muti-GPUs

### ISSUE THREAD

**Issue by herbiezhao** [Tencent/PocketFlow#26]
I have configured docker and nvidia-docker, and pulled uber/horovod, when I run command"sudo ./scripts/run_docker.sh nets/resnet_at_ilsvrc12_run.py -n=4 --learner channel --cp_preserve_ratio 0.5 --resnet_size 18" , I got "nvidia-docker | 2018/11/07 11:25:39 Error: Error response from daemon: Get https://docker.oa.com/v2/: x509: certificate signed by unknown authority" 
How can I fix this issue, and how to prepare my training data, do I need create the directory /opt/ml/data and put ilsvrc12  training data in tfrecord format into it?

**Comment by herbiezhao** [comment]
In scripts/run_docker.sh, NV_GPU=xxx docker.oa.com/g_tfplus/horovod:python3.5 bash. Should I use "uber/horovod" instead of "docker.oa.com/g_tfplus/horovod:python3.5", because i have pulled image uber/horovod .

**Comment by jiaxiang-wu** [comment]
Yes, you should use "uber/horovod" instead of "docker.oa.com/g_tfplus/horovod:python3.5".

**Comment by jiayiliu** [comment]
Any reference for the distributed learning platform "Seven"?  I didn't find it somehow...  Thanks

**Comment by jiaxiang-wu** [comment]
@jiayiliu 
"Seven" is only available within Tencent. For users outsides Tencent, please use the local & docker mode.
