### ISSUE TITLE
Compression with self-defined models

### ISSUE THREAD

**Issue by asherRSIP** [Tencent/PocketFlow#267]
First of all I want to say that this is a very impressive repo!

I have 2 questions:
1) Do all of the compression methods work with self-defined models (also the Reinforcement Learning)?

2) I have a model which outputs on each inference a few different classifications (as opposed to one), does PocketFlow support such a network?

**Comment by jiaxiang-wu** [comment]
1. All the compression methods are expected to work with self-defined models. If you found any bug, feel free to report a issue. But, we have not yet tested with reinforcement learning models and are not sure whether it will work.
2. As long as you can define the forward pass and loss function in the ModelHelper, PocketFlow should be able to support it. Again, if there is any bug, please tell us.
