### ISSUE TITLE
I would like to know more about the dataset.

### ISSUE THREAD

**Issue by zmxzsl** [Tencent/PocketFlow#268]
I can see that the type of the ImageNet dataset needs to be converted to tfrecord from tutorial of docs，but have not other type of dataset and it's not detailed enough. i.e. pascalvoc type.Whether all types of data sets need to be converted to the tfrecord format？
I want to use labelImg data sets and trained models for deep compression.As a rookie，i hope to get more help from the documentation and help from the experts to answer this question.
I applied to join your qq group, but failed. I hope I can get the approval
Thanks

**Comment by jiaxiang-wu** [comment]
1. CIFAR-10 (binary, no preprocessing) / ILSVRC-12 (tfrecord) / PASCAL VOC (tfrecord).
2. What is your QQ number? I can invite you to join the group.

**Comment by zmxzsl** [comment]
谢谢，现在已经进群了

**Comment by jiaxiang-wu** [comment]
Okay, closing the issue.
