### ISSUE TITLE
The name of variables in net is prefixed by 'model'

### ISSUE THREAD

**Issue by as754770178** [Tencent/PocketFlow#27]
I define my net, but the name of variable is Prefixed of 'model', such as 'model/resnet_v1_110/block1/unit_1/bottleneck2_v1/conv1/BatchNorm/beta ', but it should is 'resnet_v1_110/block1/unit_1/bottleneck2_v1/conv1/BatchNorm/beta '.

`NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key model/resnet_v1_110/block1/unit_1/bottleneck2_v1/conv1/BatchNorm/beta not found in checkpoint
[[Node: model/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model/save/Const_0_0, model/save/RestoreV2/tensor_names, model/save/RestoreV2/shape_and_slices)]]
[[Node: model/save/RestoreV2/_1059 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1064_model/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]`

**Comment by jiaxiang-wu** [comment]
The checkpoint files are generated by your own code, instead of `FullPrecLearner` in PocketFlow?

A quick work-around is to rename all the variables in the checkpoint files. You may refer to the `__rename_var_scope` function from `DistillationHelper` class for a reference implementation.
Link: [https://github.com/Tencent/PocketFlow/blob/master/learners/distillation_helper.py#L123](https://github.com/Tencent/PocketFlow/blob/master/learners/distillation_helper.py#L123)

**Comment by jiaxiang-wu** [comment]
Which learner are you using? Be careful, removing the name scope "model" may cause unexpected errors.

**Comment by as754770178** [comment]
--learner dis-chn-pruned
I can not found the statement that add the prefix 'model', could you tell me.

**Comment by jiaxiang-wu** [comment]
The prefix is defined in the `AbstractLearner` class, line 64:
[https://github.com/Tencent/PocketFlow/blob/master/learners/abstract_learner.py#L64](https://github.com/Tencent/PocketFlow/blob/master/learners/abstract_learner.py#L64)

**Comment by as754770178** [comment]
OK, thanks
