### ISSUE TITLE
    from tensorflow.contrib.lite.python import lite_constants ImportError: cannot import name 'lite_constants'

### ISSUE THREAD

**Issue by tkorays** [Tencent/PocketFlow#270]
When I execute the command `./scripts/run_local.sh nets/resnet_at_cifar10_run.py`, it generates the following error: 

```
from tensorflow.contrib.lite.python import lite_constants
ImportError: cannot import name 'lite_constants'
```

**Comment by jiaxiang-wu** [comment]
The usage of lite_constants in the current version (commit: 909808b) is based on TensorFlow-1.12.0. If you are using a different version, some changes on the `import` statement may be required.

**Comment by tkorays** [comment]
I found that the `lite_constants` file is moved to `tensorflow.lite.python.lite_constants`. Thanks!

**Comment by jiayiliu** [comment]
Changed again with 1.13 ..  For reference see https://www.tensorflow.org/api_docs/python/tf/lite/constants
