### ISSUE TITLE
Question about __choose_discr_chns of DisChnPrunedLearner

### ISSUE THREAD

**Issue by llhuii** [Tencent/PocketFlow#278]
For the process of selecting the most discriminative channels for a layer:

Let's assume that the first two channels to be selected are [c0, c1], and the corresponding kernel values before selected are [w0, w1]
1. Firstly c0 is selected, fine tune current layer with the kernels [w0, 0], here the kernel of c0 is started with w0
2. Secondly c1 is selected, fine tune current layer with the kernels [w0', 0], here the kernel of c1 is started with zero.

So the started values between the first selected and the remaining selected channels in fine tuning are **discriminative**, is it **desirable** or **irrelevant**?

**Comment by jiaxiang-wu** [comment]
You can also use "w1" as the initial kernel for channel "c1". We have not yet thoroughly compare the performance difference between these two variants'.

**Comment by llhuii** [comment]
I see, thanks for your reply!
