### ISSUE TITLE
What does prefix "nb" mean in variable?

### ISSUE THREAD

**Issue by lee-bin** [Tencent/PocketFlow#279]
As in `nb_classes`, `nb_smpls_train`, `nb_smpls_val`, `nb_smpls_eval`, what does prefix `nb` mean?
Does it mean `number`? I've never seen that in English. Maybe `n` or `num` is better.

**Comment by follower** [comment]
FWIW based on [this](https://www.eiffel.org/doc/eiffel/Local_Declaration_Guidelines#Well_Known_Variable_Names) I'm guessing it means "count of" or "number of".

**Comment by jiaxiang-wu** [comment]
We use "nb" as the abbreviation of "**n**um**b**er of".

**Comment by lee-bin** [comment]
That's original, thanks.
