### ISSUE TITLE
Please provide the performance of the original model as comparison.

### ISSUE THREAD

**Issue by lee-bin** [Tencent/PocketFlow#280]
<em>Please make sure that this is a documentation issue. 

**System information**
- PocketFlow version: latest
- Doc Link: https://pocketflow.github.io/performance/

**Describe the documentation issue**

The document only lists performance after pruned, would you please provide the performance of the original model so that users can get the performance degradation directly?

**We welcome contributions by users. Will you be able to update submit a PR to fix the doc Issue?**

**Comment by jiaxiang-wu** [comment]
The classification accuracy of original models are listed in the "Pre-trained Models" page:
https://pocketflow.github.io/pre_trained_models/

**Comment by lee-bin** [comment]
Thanks, I think it's better to list baseline performance besides.

**Comment by jiaxiang-wu** [comment]
Documentation revised in PR #287.
