### ISSUE TITLE
The links of the pre-trained models are failed.

### ISSUE THREAD

**Issue by njulpc** [Tencent/PocketFlow#281]
<em>The links on the doc are failed, where can i get the pre-trained models?

**Comment by jiaxiang-wu** [comment]
The file storage service is down and we are still working on it. You can contact me via email (jonathanwu@tencent.com) and I'll send pre-trained models you needed.

**Comment by jiaxiang-wu** [comment]
For future reference, please use this link to manually download all the pre-trained models. Sorry for the inconvenience.
https://1drv.ms/f/s!Ahwjm8lejJYNuog-WymzYW-lS0GzDw
