### ISSUE TITLE
Pretrained model link broken

### ISSUE THREAD

**Issue by doitfast1006** [Tencent/PocketFlow#282]
Attempt to access https://api.ai.tencent.com/pocketflow, gives 404 Not Found error. 
https://api.ai.tencent.com seems to be not accessible.

**Comment by jiaxiang-wu** [comment]
Sorry for the inconvenience. The file storage service is down and we are still working on it. You can contact me via email (jonathanwu@tencent.com) and I'll send pre-trained models you needed.
