### ISSUE TITLE
mismatched batch_size_eval and batch_size 

### ISSUE THREAD

**Issue by yuanyuanli85** [Tencent/PocketFlow#283]
There is something wroing in calculating the iterations for evaluation.  The eval score will be incorrect when batch_size not equal to batch_size_eval.

It should be 
``` 
nb_iters = int(np.ceil(float(FLAGS.nb_smpls_eval) / FLAGS.batch_size_eval))
```

while in the code 
```
 nb_iters = int(np.ceil(float(FLAGS.nb_smpls_eval) / FLAGS.batch_size))
```

**Comment by jiaxiang-wu** [comment]
Resolved in PR #285. Thanks for pointing it out.
