### ISSUE TITLE
Single GPU card is not available on PC

### ISSUE THREAD

**Issue by Aspirinkb** [Tencent/PocketFlow#29]
The `get_idle_gpus.py` in `utils` folder is about to detect how many GPU cards are available on the machine. For many users, there is only one GPU card on their PC for graphical display which leads no GPU available (the only one is busy). So, we should fix the issue by change the way of detecting available GPUs.

**Comment by Aspirinkb** [comment]
I have a GTX 1080 on my PC for training. So I comment the `busy_gpus.append(sub_strs[1])` line and add a `pass` line to ignore the  busy GPU detection.

**Comment by jiaxiang-wu** [comment]
Enhancement required: change the way of detecting available GPUs.

**Comment by jiaxiang-wu** [comment]
Resolved in the pull request #75
