### ISSUE TITLE
Link to pre-trained models broken

### ISSUE THREAD

**Issue by StanHR** [Tencent/PocketFlow#290]
- Doc Link: https://pocketflow.github.io/pre_trained_models/

- The link to the pre-trained models on the above mentioned page return a 404 error. 

- I see this issue was reported about 27 days ago in #281 , but the links are still broken.

**Comment by ndcuong91** [comment]
any update on this issue? i spent a week downloading imagenet but i still can not run an example

**Comment by jiaxiang-wu** [comment]
@StanHR @titikid 
Please use this link to download all the pre-trained models. Sorry for the inconvenience.
https://1drv.ms/f/s!Ahwjm8lejJYNuog-WymzYW-lS0GzDw
