### ISSUE TITLE
cifar10_channel pruned 的示例，通道剪枝(channel_pruning) 导出修改了计算图之后，速度比之前的更慢了！

### ISSUE THREAD

**Issue by hudengjunai** [Tencent/PocketFlow#307]
如题所示：对cifar10-resnet18 例子中模型进行通道剪枝，由于剪枝之后模型更改中将全为0的filter和对应feature_map通道删除，采用了1x1 kernel filter channel 选择方式，相比之前增加了一层。导出的frozen pb 计算图在GPU上速度变慢了，有什么解决方案吗？

**Comment by hudengjunai** [comment]
> 如题所示：对cifar10-resnet18 例子中模型进行通道剪枝，由于剪枝之后模型更改中将全为0的filter和对应feature_map通道删除，采用了1x1 kernel filter channel 选择方式，相比之前增加了一层。导出的frozen pb 计算图在GPU上速度变慢了，有什么解决方案吗？
问题已经在 #119 解决了。

**Comment by A1exy** [comment]
@hudengjunai  由于剪枝之后模型更改中将全为0的filter和对应feature_map通道删除，采用了1x1 kernel filter channel 选择方式。请问为什么需要加这个1x1 kernel filter channel 选择方式，不太懂，请教下。
