### ISSUE TITLE
TF Version compatibility

### ISSUE THREAD

**Issue by jiayiliu** [Tencent/PocketFlow#316]
**Describe the bug**
I am not sure where part fails, but I do think this is related to newer TF versions.

**To Reproduce**

When I ran `scripts/run_local.sh nets/resnet_at_cifar10_run.py`. I got the following error with TF version 1.14 (and thereafter), whereas no problem at all with 1.13:

> ValueError: Tensor("Const:0", shape=(1, 1, 3), dtype=float32) must be from the same graph as Tensor("data/ExperimentalParallelInterleaveDataset:0", shape=(), dtype=variant).

**Expected behavior**
Do you have plan for Tensorflow version 2.0 support?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Titan X
 - Python3

**Comment by yuanyuanli85** [comment]
As I know, this repo is not activately maintained by Tecent team. so,  my guessing is it may not have the tf2.0 support plan in short term.

**Comment by jiayiliu** [comment]
Thanks, so sad to see there is no further development on this project..
