### ISSUE TITLE
why it reports FLAGS.data_dir_local is None?

### ISSUE THREAD

**Issue by zhangqianYY** [Tencent/PocketFlow#37]
hello, i run the example resnet_at_cifar10, and use command './scripts/run_docker.sh nets/resnet_at_cifar10_run.py', i copyed path.conf.template and rename path.conf in PocketFlow-master file,and i set data_dir_local_cifar10 = /media/gavin/Data/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin/   in path.conf  file ,but the log shows FLAGS.data_dir_local is None ?
the log : 
Traceback (most recent call last):
  File "utils/get_path_args.py", line 51, in <module>
    assert len(key_n_value) == 2, 'each line must contains exactly one \' = \''
AssertionError: each line must contains exactly one ' = '
Python script: nets/resnet_at_cifar10_run.py
# of GPUs: 1
extra arguments:  
'nets/resnet_at_cifar10_run.py' -> 'main.py'
multi-GPU training disabled
[WARNING] TF-Plus & Horovod cannot be imported; multi-GPU training is unsupported
INFO:tensorflow:FLAGS:
INFO:tensorflow:data_disk: local
INFO:tensorflow:data_hdfs_host: None
INFO:tensorflow:data_dir_local: None
INFO:tensorflow:data_dir_hdfs: None
INFO:tensorflow:cycle_length: 4
INFO:tensorflow:nb_threads: 8
INFO:tensorflow:buffer_size: 1024
INFO:tensorflow:prefetch_size: 8
INFO:tensorflow:nb_classes: 10
INFO:tensorflow:nb_smpls_train: 50000
INFO:tensorflow:nb_smpls_val: 5000
INFO:tensorflow:nb_smpls_eval: 10000
INFO:tensorflow:batch_size: 128
INFO:tensorflow:batch_size_eval: 100
INFO:tensorflow:resnet_size: 20
INFO:tensorflow:lrn_rate_init: 0.1
INFO:tensorflow:batch_size_norm: 128.0
INFO:tensorflow:momentum: 0.9
INFO:tensorflow:loss_w_dcy: 0.0002
INFO:tensorflow:model_http_url: None
INFO:tensorflow:summ_step: 100
INFO:tensorflow:save_step: 10000
INFO:tensorflow:save_path: ./models/model.ckpt
INFO:tensorflow:save_path_eval: ./models_eval/model.ckpt
INFO:tensorflow:enbl_dst: False
INFO:tensorflow:enbl_warm_start: False
INFO:tensorflow:loss_w_dst: 4.0
INFO:tensorflow:tempr_dst: 4.0
INFO:tensorflow:save_path_dst: ./models_dst/model.ckpt
INFO:tensorflow:nb_epochs_rat: 1.0
INFO:tensorflow:ddpg_actor_depth: 2
INFO:tensorflow:ddpg_actor_width: 64
INFO:tensorflow:ddpg_critic_depth: 2
INFO:tensorflow:ddpg_critic_width: 64
INFO:tensorflow:ddpg_noise_type: param
INFO:tensorflow:ddpg_noise_prtl: tdecy
INFO:tensorflow:ddpg_noise_std_init: 1.0
INFO:tensorflow:ddpg_noise_dst_finl: 0.01
INFO:tensorflow:ddpg_noise_adpt_rat: 1.03
INFO:tensorflow:ddpg_noise_std_finl: 1e-05
INFO:tensorflow:ddpg_rms_eps: 0.0001
INFO:tensorflow:ddpg_tau: 0.01
INFO:tensorflow:ddpg_gamma: 0.9
INFO:tensorflow:ddpg_lrn_rate: 0.001
INFO:tensorflow:ddpg_loss_w_dcy: 0.0
INFO:tensorflow:ddpg_record_step: 1
INFO:tensorflow:ddpg_batch_size: 64
INFO:tensorflow:ddpg_enbl_bsln_func: True
INFO:tensorflow:ddpg_bsln_decy_rate: 0.95
INFO:tensorflow:ws_save_path: ./models_ws/model.ckpt
INFO:tensorflow:ws_prune_ratio: 0.75
INFO:tensorflow:ws_prune_ratio_prtl: optimal
INFO:tensorflow:ws_nb_rlouts: 200
INFO:tensorflow:ws_nb_rlouts_min: 50
INFO:tensorflow:ws_reward_type: single-obj
INFO:tensorflow:ws_lrn_rate_rg: 0.03
INFO:tensorflow:ws_nb_iters_rg: 20
INFO:tensorflow:ws_lrn_rate_ft: 0.0003
INFO:tensorflow:ws_nb_iters_ft: 400
INFO:tensorflow:ws_nb_iters_feval: 25
INFO:tensorflow:ws_prune_ratio_exp: 3.0
INFO:tensorflow:ws_iter_ratio_beg: 0.1
INFO:tensorflow:ws_iter_ratio_end: 0.5
INFO:tensorflow:ws_mask_update_step: 500.0
INFO:tensorflow:cp_lasso: True
INFO:tensorflow:cp_quadruple: False
INFO:tensorflow:cp_reward_policy: accuracy
INFO:tensorflow:cp_nb_points_per_layer: 10
INFO:tensorflow:cp_nb_batches: 60
INFO:tensorflow:cp_prune_option: auto
INFO:tensorflow:cp_prune_list_file: ratio.list
INFO:tensorflow:cp_best_path: ./models/best_model.ckpt
INFO:tensorflow:cp_original_path: ./models/original_model.ckpt
INFO:tensorflow:cp_preserve_ratio: 0.5
INFO:tensorflow:cp_uniform_preserve_ratio: 0.6
INFO:tensorflow:cp_noise_tolerance: 0.15
INFO:tensorflow:cp_lrn_rate_ft: 0.0001
INFO:tensorflow:cp_nb_iters_ft_ratio: 0.2
INFO:tensorflow:cp_finetune: False
INFO:tensorflow:cp_retrain: False
INFO:tensorflow:cp_list_group: 1000
INFO:tensorflow:cp_nb_rlouts: 200
INFO:tensorflow:cp_nb_rlouts_min: 50
INFO:tensorflow:dcp_save_path: ./models_dcp/model.ckpt
INFO:tensorflow:dcp_save_path_eval: ./models_dcp_eval/model.ckpt
INFO:tensorflow:dcp_prune_ratio: 0.5
INFO:tensorflow:dcp_nb_stages: 3
INFO:tensorflow:dcp_lrn_rate_adam: 0.001
INFO:tensorflow:dcp_nb_iters_block: 10000
INFO:tensorflow:dcp_nb_iters_layer: 500
INFO:tensorflow:uql_equivalent_bits: 4
INFO:tensorflow:uql_nb_rlouts: 200
INFO:tensorflow:uql_w_bit_min: 2
INFO:tensorflow:uql_w_bit_max: 8
INFO:tensorflow:uql_tune_layerwise_steps: 100
INFO:tensorflow:uql_tune_global_steps: 2000
INFO:tensorflow:uql_tune_save_path: ./rl_tune_models/model.ckpt
INFO:tensorflow:uql_tune_disp_steps: 300
INFO:tensorflow:uql_enbl_random_layers: True
INFO:tensorflow:uql_enbl_rl_agent: False
INFO:tensorflow:uql_enbl_rl_global_tune: True
INFO:tensorflow:uql_enbl_rl_layerwise_tune: False
INFO:tensorflow:uql_weight_bits: 4
INFO:tensorflow:uql_activation_bits: 32
INFO:tensorflow:uql_use_buckets: False
INFO:tensorflow:uql_bucket_size: 256
INFO:tensorflow:uql_quant_epochs: 60
INFO:tensorflow:uql_save_quant_model_path: ./uql_quant_models/uql_quant_model.ckpt
INFO:tensorflow:uql_quantize_all_layers: False
INFO:tensorflow:uql_bucket_type: channel
INFO:tensorflow:uqtf_save_path: ./models_uqtf/model.ckpt
INFO:tensorflow:uqtf_save_path_eval: ./models_uqtf_eval/model.ckpt
INFO:tensorflow:uqtf_weight_bits: 8
INFO:tensorflow:uqtf_activation_bits: 8
INFO:tensorflow:uqtf_quant_delay: 0
INFO:tensorflow:uqtf_freeze_bn_delay: None
INFO:tensorflow:uqtf_lrn_rate_dcy: 0.01
INFO:tensorflow:nuql_equivalent_bits: 4
INFO:tensorflow:nuql_nb_rlouts: 200
INFO:tensorflow:nuql_w_bit_min: 2
INFO:tensorflow:nuql_w_bit_max: 8
INFO:tensorflow:nuql_tune_layerwise_steps: 100
INFO:tensorflow:nuql_tune_global_steps: 2101
INFO:tensorflow:nuql_tune_save_path: ./rl_tune_models/model.ckpt
INFO:tensorflow:nuql_tune_disp_steps: 300
INFO:tensorflow:nuql_enbl_random_layers: True
INFO:tensorflow:nuql_enbl_rl_agent: False
INFO:tensorflow:nuql_enbl_rl_global_tune: True
INFO:tensorflow:nuql_enbl_rl_layerwise_tune: False
INFO:tensorflow:nuql_init_style: quantile
INFO:tensorflow:nuql_opt_mode: weights
INFO:tensorflow:nuql_weight_bits: 4
INFO:tensorflow:nuql_activation_bits: 32
INFO:tensorflow:nuql_use_buckets: False
INFO:tensorflow:nuql_bucket_size: 256
INFO:tensorflow:nuql_quant_epochs: 60
INFO:tensorflow:nuql_save_quant_model_path: ./nuql_quant_models/model.ckpt
INFO:tensorflow:nuql_quantize_all_layers: False
INFO:tensorflow:nuql_bucket_type: split
INFO:tensorflow:log_dir: ./logs
INFO:tensorflow:enbl_multi_gpu: False
INFO:tensorflow:learner: full-prec
INFO:tensorflow:exec_mode: train
INFO:tensorflow:debug: False
INFO:tensorflow:h: False
INFO:tensorflow:help: False
INFO:tensorflow:helpfull: False
INFO:tensorflow:helpshort: False
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 50, in main
    model_helper = ModelHelper()
  File "/home/gavin/PocketFlow-master/nets/resnet_at_cifar10.py", line 75, in __init__
    self.dataset_train = Cifar10Dataset(is_train=True)
  File "/home/gavin/PocketFlow-master/datasets/cifar10_dataset.py", line 87, in __init__
    assert FLAGS.data_dir_local is not None, '<FLAGS.data_dir_local> must not be None'
AssertionError: <FLAGS.data_dir_local> must not be None

**Comment by zhangqianYY** [comment]
> Can you post the full content of your `path.conf` file?
the follow is full content of 'path.conf':


# Notes on HDFS-related configurations:
# * data_hdfs_host:
#     HDFS host for remote datasets.
#     This will be used by TensorFlow's data input pipeline.
#     Format: hdfs://IP_Address:Port
#     Leave 'None' unchanged if HDFS is not availabe.
# * model_http_url:
#     HTTP/HTTPS url for remote model files.
#     This will be used to download pre-trained models via <wget>.
#     Format: http://aaa.bbb.ccc OR https://aaa.bbb.ccc
#     Set it to 'None' if such connection is not available.
#
# How to setup the directory path:
# * If a data directory path exists, then replace 'None' with the actual path, e.g.:
#     data_dir_local_cifar10 = /home/user_name/datasets/cifar-10/cifar-10-batches-bin
#   which setups the path to the CIFAR-10 dataset on the local machine.
# * Otherwise, leave 'None' unchanged.

# data files
data_hdfs_host = None
data_dir_local_cifar10 = /media/gavin/Data/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin/
data_dir_hdfs_cifar10 = None
data_dir_seven_cifar10 = None
data_dir_docker_cifar10 = /opt/ml/data  # DO NOT EDIT
data_dir_local_ilsvrc12 = /media/gavin/Data-pro/imagenet_tfrecords   # this line has been edited!
data_dir_hdfs_ilsvrc12 = None
data_dir_seven_ilsvrc12 = None
data_dir_docker_ilsvrc12 = /opt/ml/data  # DO NOT EDIT

# model files
model_http_url = https://api.ai.tencent.com/pocketflow

**Comment by zhangqianYY** [comment]
> Can you post the full content of your `path.conf` file?

the follow is full content of 'path.conf':

# Notes on HDFS-related configurations:
# * data_hdfs_host:
#     HDFS host for remote datasets.
#     This will be used by TensorFlow's data input pipeline.
#     Format: hdfs://IP_Address:Port
#     Leave 'None' unchanged if HDFS is not availabe.
# * model_http_url:
#     HTTP/HTTPS url for remote model files.
#     This will be used to download pre-trained models via <wget>.
#     Format: http://aaa.bbb.ccc OR https://aaa.bbb.ccc
#     Set it to 'None' if such connection is not available.
#
# How to setup the directory path:
# * If a data directory path exists, then replace 'None' with the actual path, e.g.:
#     data_dir_local_cifar10 = /home/user_name/datasets/cifar-10/cifar-10-batches-bin
#   which setups the path to the CIFAR-10 dataset on the local machine.
# * Otherwise, leave 'None' unchanged.

# data files
data_hdfs_host = None
data_dir_local_cifar10 =/home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
data_dir_hdfs_cifar10 = None
data_dir_seven_cifar10 = None
data_dir_docker_cifar10 = /opt/ml/data  # DO NOT EDIT
data_dir_local_ilsvrc12 = None
data_dir_hdfs_ilsvrc12 = None
data_dir_seven_ilsvrc12 = None
data_dir_docker_ilsvrc12 = /opt/ml/data  # DO NOT EDIT

# model files
model_http_url = https://api.ai.tencent.com/pocketflow

**Comment by zhangqianYY** [comment]
the following is full content of 'path.conf':

### # Notes on HDFS-related configurations:
### # * data_hdfs_host:
### #     HDFS host for remote datasets.
### #     This will be used by TensorFlow's data input pipeline.
### #     Format: hdfs://IP_Address:Port
### #     Leave 'None' unchanged if HDFS is not availabe.
### # * model_http_url:
### #     HTTP/HTTPS url for remote model files.
### #     This will be used to download pre-trained models via <wget>.
### #     Format: http://aaa.bbb.ccc OR https://aaa.bbb.ccc
### #     Set it to 'None' if such connection is not available.
### #
### # How to setup the directory path:
### # * If a data directory path exists, then replace 'None' with the actual path, e.g.:
### #     data_dir_local_cifar10 = /home/user_name/datasets/cifar-10/cifar-10-batches-bin
### #   which setups the path to the CIFAR-10 dataset on the local machine.
### # * Otherwise, leave 'None' unchanged.

### # data files
data_hdfs_host = None
data_dir_local_cifar10=/home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
data_dir_hdfs_cifar10 = None
data_dir_seven_cifar10 = None
data_dir_docker_cifar10 = /opt/ml/data  # DO NOT EDIT
data_dir_local_ilsvrc12 = None
data_dir_hdfs_ilsvrc12 = None
data_dir_seven_ilsvrc12 = None
data_dir_docker_ilsvrc12 = /opt/ml/data  # DO NOT EDIT

### # model files
model_http_url = https://api.ai.tencent.com/pocketflow

> Can you post the full content of your `path.conf` file?



> Can you post the full content of your `path.conf` file?

**Comment by jiaxiang-wu** [comment]
Please change
``` Python
data_dir_local_cifar10=/home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
```
into
``` Python
data_dir_local_cifar10 = /home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
```
which surrounds "=" with two whitespaces, as required by `utils/get_path_args.py`.

[https://github.com/Tencent/PocketFlow/blob/master/utils/get_path_args.py#L50](https://github.com/Tencent/PocketFlow/blob/master/utils/get_path_args.py#L50)

**Comment by zhangqianYY** [comment]
> Please change
> 
> ```python
> data_dir_local_cifar10=/home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
> ```
> 
> into
> 
> ```python
> data_dir_local_cifar10 = /home/gavin/PycharmProjects/datasets/cifar10_data/cifar-10-batches-bin
> ```
> 
> which surrounds "=" with two whitespaces, as required by `utils/get_path_args.py`.
> 
> https://github.com/Tencent/PocketFlow/blob/master/utils/get_path_args.py#L50

I succeeded,thank you very much for your help

**Comment by jiaxiang-wu** [comment]
You're welcome.
