### ISSUE TITLE
model path

### ISSUE THREAD

**Issue by as754770178** [Tencent/PocketFlow#43]
1. `Discrimination-aware Channel Pruning` have the parameter `dcp_save_path` and `dcp_save_path_eval` to set the save path of compressed model. Other way in PocketFlow, whether have the similiar parameter to set the save path of compressed model.

2. The parameter `save_path` in file `abstract_learner.py` is mean the save path of the full-precision uncompressed network ?  What's the function of parameter `save_path_eval` ?

**Comment by jiaxiang-wu** [comment]
1. We are considering unifying the save path arguments for model compression components. For instance, all model compression components should write the training graph (and variables) to `mc_save_path` and the evaluation graph (and variables) to `mc_save_path_eval`.

2. Yes, `save_path` means the save path of the full-precision uncompressed network, particularly the training graph (and variables). The evaluation graph (and variables) is written to `save_path_eval`.

The reason for saving both training and evaluation graph is that, to continue from previously-aborted training, you need the training graph, and to export a TF-Lite model from checkpoint files, you need the evaluation graph.

**Comment by jiaxiang-wu** [comment]
1. `save_path` & `save_path_eval` is written by the `FullPrecLearner`, and `dcp_save_path` & `dcp_save_path_eval` is written by the `DisChnPrunedLearner`. When running model compression components, only `save_path` is required to load a pre-trained uncompressed model.
2. As mentioned above, for model compression components, only `save_path` is required. You do not need to provide the `save_path_eval`. All save paths with a suffix "_eval" is only used for exporting TF-Lite models. They are not required in the training process.

**Comment by as754770178** [comment]
Where define the save path of compressed model other than `DisChnPrunedLearner` mode?

**Comment by as754770178** [comment]
I don't fount the parameter, but I want to know you how to specify the path? and I found some variable w.r.t path is specified to fixed value, such as `channel_pruned_path = './models/pruned_model.ckpt'
    best_model_path = './models/best_model.ckpt'`, Can you tell me what they means?

**Comment by psyyz10** [comment]
@as754770178 in `ChannelPrunedLearner`, `best_model_path` is the parameter that specify the save path of compressed model and `channel_pruned_path ` saved some intermediate results

**Comment by as754770178** [comment]
I conclude the parameter about the path.
1. `ChannelPrunedLearner` 
`best_model_path` is the parameter that specify the save path of compressed model and `channel_pruned_path` saved some intermediate results. Now, `best_model_path` changed to `cp_best_paht`; `channel_pruned_path` changed to `cp_channel_pruned_path`. But I doubt that what does `cp_original_path` mean, whether it conflict with `save_path`.
2. `UniformQuanTFLearner`
`uqtf_save_path_eval` is the parameter that specify the save path of compressed model and `uqtf_save_path` saved some intermediate results. 
3. `DisChnPrunedLearner`
`dcp_save_path_eval` is the parameter that specify the save path of compressed model and `dcp_save_path` saved some intermediate results. 
4. `FullPrecLearner`
`save_path_eval` is the parameter that specify the save path of compressed model and `save_path` saved some intermediate results. 

5. `NonUniformQuantLearner`
`nuql_save_quant_model_path` is the parameter that specify the save path of compressed model. 
6. `UniformQuantLearner`
`uql_save_quant_model_path` is the parameter that specify the save path of compressed model. 
7. `WeightSparseLearner`
`ws_save_path` is the parameter that specify the save path of compressed model. 
Why  `NonUniformQuantLearner`, `UniformQuantLearner` and `WeightSparseLearner` don't have the parameter to set the path saved some intermediate results. 

I don't know whether my summary is correct?

**Comment by psyyz10** [comment]
@as754770178 `cp_original_path` is also a path to save temporal model, but the different temporal model from `cp_channel_pruned_path`. User may do some operations, for example changed model scope, and which can be saved to `cp_original_path`.
