### ISSUE TITLE
can pocketflow be used for object detection model

### ISSUE THREAD

**Issue by AllenDun** [Tencent/PocketFlow#44]
thanks for the great work. Many tasks in industry scene are object detections. Can pocketflow be used for object detection model, such as ssd, faster rcnn?

**Comment by jiaxiang-wu** [comment]
Enhancement required: add support for object detection models.

**Comment by jiaxiangxu** [comment]
Excuse me, what is the fundamental difference between object detection models and image classification models such that the current PocketFlow cannot support object detection models?

**Comment by jiaxiang-wu** [comment]
Some object detection models, *e.g.* Faster R-CNN and R-FCN, require multiple training stages (RPN -> detection model -> RPN with shared conv. layers -> detection model with shared conv. layers). This is not yet supported in PocketFlow.

**Comment by jiaxiang-wu** [comment]
@jiaxiangxu 
We have not tested on SSD on YOLO yet, so we are not sure whether PocketFlow can be directly used for these two models.

**Comment by jiaxiang-wu** [comment]
SSD models have been supported in the latest master branch.

**Comment by as754770178** [comment]
The compression on SSD is only  quantization?  Is there document about quantization on SSD？

**Comment by jiaxiang-wu** [comment]
Current code only supports uniform quantization, but we will release the support for channel pruning shortly. The document for uniform quantization and channel pruning will be released together.

**Comment by as754770178** [comment]
When you release the document, I hope you can inform me.

**Comment by jiaxiang-wu** [comment]
@as754770178 No problem.

**Comment by howtocodewang** [comment]
@jiaxiang-wu Can you tell me when the document for object detection network compression will be released.

**Comment by sourman** [comment]
@jiaxiang-wu I am curious if channel pruning has been released. I would like to try it for Mobilenet SSD architecture

**Comment by smohan10** [comment]
I'm curious to know if channel pruning can be done on SSD model on COCO dataset using Pocketflow. Has anyone tried it and were successful?
