### ISSUE TITLE
how to set my data path

### ISSUE THREAD

**Issue by 1448643857** [Tencent/PocketFlow#45]
I want to train models in my data, I want to know how to set path to my data,thank u

**Comment by as754770178** [comment]
set data path in `path.conf` file, you can reference `path.conf.template`  file

**Comment by jiaxiang-wu** [comment]
@1448643857 
If you are using data sets besides CIFAR-10 and ILSVRC-12, then you need to define a new `ModelHelper` class to tell PocketFlow how to parse your data, as other `ModelHelper` classes defined in the "./nets" sub-directory.

**Comment by 1448643857** [comment]
thank u
