### ISSUE TITLE
What's the training parameters for MobileNetV2 8 Bit Fixed-point?

### ISSUE THREAD

**Issue by terrydlca** [Tencent/PocketFlow#48]
Thanks for sharing the great work. What's the training parameters for MobileNetV2 8 Bit Fixed-point to get the 72.26% accuracy?

Is this correct? Any other parameter needed?

sh ./scripts/run_local.sh nets/resnet_at_ilsvrc12_run.py \
--learner=uniform \
--data_disk local \
--data_dir_local ${PF_ILSVRC12_LOCAL} \
--uql_weight_bits=8 \
--uql_activation_bits=8 \

**Comment by terrydlca** [comment]
@jiaxiang-wu Thanks for the quick response. If chosen the run_local.sh, is there any other hyper-parameter changes needed to reproduce the 72% accuracy, for example initial learning rate? 

Also, saw there are a typo in the https://pocketflow.github.io/tutorial/, "find 4,096 training files" should be "find 1,024 training files" based on this link: https://github.com/tensorflow/models/tree/master/research/inception#getting-started.

**Comment by jiaxiang-wu** [comment]
The above command should be enough. No more hyper-parameter needed. Thanks for pointing out the typo.

**Comment by jiaxiang-wu** [comment]
TODO: change the number of training files in the tutorial from 4096 to 1024.

**Comment by terrydlca** [comment]
@jiaxiang-wu Thanks, here is the results after training more than 12 hours using local mode. The Top1 accuracy is very low, and the loss is still very high, also why the optimal weight quantization is shown as 4? Saw the published accuracy number for the MobileNetV2 is 8 bit (MobileNet-v2 | 71.84% | 90.60% | 72.26% (+0.42%) | 90.77% (+0.17%)), right? 

INFO:tensorflow:loss: 10.742256164550781
INFO:tensorflow:accuracy: 0.01297999918460846
INFO:tensorflow:Optimal Weight Quantization:[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

And also add the intermediate training logs:

.0503 | acc_top1 = 0.0000 | acc_top5 = 0.0156 | speed = 172.22 pics / sec
INFO:tensorflow:iter #142100: lr = 4.500000e-07 | model_loss = 7.2648 | loss = 7.2648 | acc_top1 = 0.0000 | acc_top5 = 0.0312 | speed = 170.89 pics / sec
INFO:tensorflow:iter #142200: lr = 4.500000e-07 | model_loss = 7.1522 | loss = 7.1522 | acc_top1 = 0.0000 | acc_top5 = 0.0312 | speed = 172.06 pics / sec
INFO:tensorflow:iter #142300: lr = 4.500000e-07 | model_loss = 7.1517 | loss = 7.1517 | acc_top1 = 0.0000 | acc_top5 = 0.0625 | speed = 172.49 pics / sec
INFO:tensorflow:iter #142400: lr = 4.500000e-07 | model_loss = 6.9467 | loss = 6.9467 | acc_top1 = 0.0312 | acc_top5 = 0.0469 | speed = 174.34 pics / sec
INFO:tensorflow:iter #142500: lr = 4.500000e-07 | model_loss = 7.1331 | loss = 7.1331 | acc_top1 = 0.0000 | acc_top5 = 0.0312 | speed = 173.76 pics / sec

BTW, I followed the exact local mode command as you mentioned for the above training results.

**Comment by terrydlca** [comment]
@jiaxiang-wu I knew the root cause why  the weight quantization is 4 bits now, the typed cmd missed the "-tf" due to the "-" between uniform and tf. It's working properly now. Thanks.

**Comment by jiaxiang-wu** [comment]
@terrydlca Good to know it works.

**Comment by terrydlca** [comment]
@jiaxiang-wu Another question is there are errors when convert the trained mobilenet_v2 model to tflite format. Do you have an example cmd for mobilenet_v2 tflite conversion?

python tools/conversion/export_quant_tflite_model.py --model_dir ./models_uqtf

Traceback (most recent call last):
  File "tools/conversion/export_quant_tflite_model.py", line 271, in <module>
    tf.app.run()
 File "tools/conversion/export_quant_tflite_model.py", line 249, in main
    input_name, input_shape = get_input_name_n_shape(file_path_meta)
  File "tools/conversion/export_quant_tflite_model.py", line 63, in get_input_name_n_shape
    net_input = tf.get_collection(FLAGS.input_coll)[0]
IndexError: list index out of range

**Comment by jiaxiang-wu** [comment]
@terrydlca 
You should specify the save path for the evaluation graph, instead of the training graph, of the compressed model, which can be exported to the TF-Lite model.

``` bash
$ python tools/conversion/export_quant_tflite_model.py --model_dir ./models_uqtf_eval
```

**Comment by terrydlca** [comment]
@jiaxiang-wu Thanks, it works now.

**Comment by jiaxiang-wu** [comment]
Resolved in the pull request https://github.com/Tencent/PocketFlow/pull/66

**Comment by alekhyadarsi** [comment]
hi jiaxiang-wu
where will be the compressed model saved??i.e weigts and cfg file for testing model
