### ISSUE TITLE
is this fully_quantized model?

### ISSUE THREAD

**Issue by wangxianrui** [Tencent/PocketFlow#49]
Are  quantized models  fully_quantized?  
can they run on chips that only integer operation  supported?
thanks.

**Comment by jiaxiang-wu** [comment]
* For compressed models generated by `UniformQuantTFLearner`, all the operations that match TensorFlow's rule for `tf.contrib.quantize.experimental_create_training_graph` will be quantized. For MobileNet-v1 and MobileNet-v2, all operations will be quantized; for ResNet models, some operation may not be quantized (at least this is true for TensorFlow-1.10.0).
* For TF-Lite models generated by `tools/conversion/export_quant_tflite_model.py` with the `enbl_post_quant` option enabled, all operations will be quantized.
* By "chips", which hardware do you refer to exactly? Do you have the corresponding DL inference engine for that hardware, with integer operations supported?

**Comment by wangxianrui** [comment]
em..I am just working on a project, and the other requires a fully_quantized model to run on their 'chips', but i do not know exactly.

**Comment by jiaxiang-wu** [comment]
In short, you need to know which inference engine they are using, and then try to obtain a fully-quantized model (maybe not from PocketFlow) that can be parsed by that inference engine.

**Comment by Aspirinkb** [comment]
Will you give the details of how the quantized model weights are saved and how they run mathmatically? So one can implement the model on some specific devices for inference acceleration.

**Comment by jiaxiang-wu** [comment]
For `UniformQuantTFLearner`, we are using TensorFlow's quantization-aware training API, *i.e.*:
``` Python
tf.contrib.quantize.experimental_create_training_graph(
    input_graph=None,
    weight_bits=8,
    activation_bits=8,
    quant_delay=0,
    freeze_bn_delay=None,
    scope=None
)
```
to modify the graph and insert quantization operations. You may refer to their documentations to see how it works in details.

**Comment by Aspirinkb** [comment]
If I prefer to use `UniformQuantLearner` of PocketFlow's to quantize models rather than TensorFlow's, where can I get the details of the quantized models about their weights, graphs and so on? Do you give some inference implements about that？If not, I think it is a necessary feature of PocketFlow.  What do you think?

**Comment by wangxianrui** [comment]
the `UniformQuantLearner` in PocketFlow just reuse Tensorflow's API, I think.  If you don't want to use it, you can also try another, such as .. `UniformQuantizedLearner` and `NonUniformQuantizedLearner`, you can get detail in https://pocketflow.github.io/

**Comment by wangxianrui** [comment]
I also have a question about `Uniform Quantization Learner`, is this method just quantize weight and activation?  So, the data flows int network is still float type， instead ofquantize bits such as 8 or 4 bits?
thanks!

**Comment by jiaxiang-wu** [comment]
@Aspirinkb 
`UniformQuantLearner` is mainly for research purpose (for instance, to see how well RL can determine the bit-width allocation strategy). An efficient inference implementation heavily relies on the hardware platform and requires lots on work. For efficient deployment, we recommend you to use `UniformQuantTFLearner`, which can be deployed under the TensorFlow Lite framework.
