### ISSUE TITLE
"ValueError: unrecognized learner's name: tf-uniform“ . In tutorial,  --learner  specification is not accordant with code

### ISSUE THREAD

**Issue by LinkenMu** [Tencent/PocketFlow#50]
./scripts/run_local.sh nets/lenet_at_cifar10_run.py --learner tf-uniform
the command will get below:
  File "/home/cv/PocketFlow/learners/learner_utils.py", line 58, in create_learner
    raise ValueError('unrecognized learner\'s name: ' + FLAGS.learner)
ValueError: unrecognized learner's name: tf-uniform

https://pocketflow.github.io/tutorial/#tutorial
Learner name  "tf-uniform"  is differ form  learner_utils.py  line 54

in learner_utils.py  line 54
 elif FLAGS.learner == 'uniform-tf':
    learner = UniformQuantTFLearner(sm_writer, model_helper)

**Comment by jiaxiang-wu** [comment]
Sorry for the typo in the documentation. Please use "uniform-tf" to choose `UniformQuantTFLearner` for model compression.

**Comment by jiaxiang-wu** [comment]
TODO: change the name of `UniformQuantTFLearner` from "tf-uniform" to "uniform-tf".
