### ISSUE TITLE
Question on the uniform quantization

### ISSUE THREAD

**Issue by Maximilianxu** [Tencent/PocketFlow#57]
The code in function `__uniform_quantize()` in the file 'utils.py' in 'uniform_quantization' directory shows that the quantized weight or activation is also coded as the same type as the original tensor. For example, if the original tensor has a type `float32`, the quantized one will be `float32` too. Why does not the quantized tensor has a type `int` and the predict process is computed with only integers? 
So, does Pocketflow learn a quantization strategy and if we want computation with integers only,  it should be accomplished with tools like TFLite, which transforms the model into a '.pb' format?

**Comment by jiaxiang-wu** [comment]
During training, weights in the quantized model are also stored as floating-point numbers. For integer-only computation, you need to export checkpoint files into TF-Lite models (*.tflite format), and use TensorFlow Lite Interpreter for inference.
