### ISSUE TITLE
Does it support Mobilenet-v2-SSD ?

### ISSUE THREAD

**Issue by haikuoyao** [Tencent/PocketFlow#58]
It's an amzing work. 

Does it support Mobilenet-v2-SSD?
I'm using it for object detection. 
I saw PocketFlow doesn't support yolo, etc.

Thanks.

**Comment by jiaxiang-wu** [comment]
PocketFlow does not support object detection models, for now. We are working on this right now.

Duplicated with #44

**Comment by Ariel-JUAN** [comment]
Does it support DenseNet compression？

**Comment by jiaxiang-wu** [comment]
@Ariel-JUAN 
You mean DenseNet for image classification? This can be suppported by adding a new `ModelHelper` class, similar to those defined in the "./nets" directory.

**Comment by Ariel-JUAN** [comment]
@jiaxiang-wu  Thanks~
