### ISSUE TITLE
I want to compress my own model such as Gan's  or mtcnn ,how can I change the code?can you supply a demo or document about how can we change the file to work on my own model?

### ISSUE THREAD

**Issue by sunzhe09** [Tencent/PocketFlow#59]
I'm trying to compress a unet-like model ,but i don't know how to edit it

**Comment by jiaxiang-wu** [comment]
If your model can be trained in an end-to-end manner, you can try to implement a new `ModelHelper` class, defining the data input pipepline, forward computation, and loss function, similar to those defined in the "./nets" directory. We are adding a documentation page to demonstrate how to incorporate customized models and data sets into PocketFlow.

**Comment by jiaxiang-wu** [comment]
Doc required: demonstrate how to incorporate customized models and data sets into PocketFlow.

**Comment by ginger0106** [comment]
hi, when the documents will be released?

**Comment by ginger0106** [comment]
to compress my own model, we need to implement a new `ModelHelper` and `setup_lrn_rate`, does it right? Anything else needed? Thanks

**Comment by jiaxiang-wu** [comment]
@ginger0106 @sunzhe09 
We have added documentation to demonstrate how to incorporate self-defined data sets and models into PocketFlow. See [here](https://pocketflow.github.io/self_defined_models/) for details.
