### ISSUE TITLE
questions about TensorFlow Quantization Wrapper

### ISSUE THREAD

**Issue by wangxianrui** [Tencent/PocketFlow#61]
em.. I want to export *.pb & *.tflite models from checkpoint files, so I run this command according the tutorial:
python tools/conversion/export_pb_tflite_models.py \
--model_dir ./models \
--input_coll inputs \
--output_coll outputs \
--quantize True
but I got an error `local variable 'file_path' referenced before assignment`
the files in ./models:
models
├── checkpoint
├── model.ckpt-97656.data-00000-of-00001
├── model.ckpt-97656.index
└── model.ckpt-97656.meta
So, can you give any idea about this?

**Comment by jiaxiang-wu** [comment]
To export *.pb & *.tflite models, your should use checkpoint files for the evaluation graph, which is stored in the "./models_cp_eval" (or "./models_dcp_eval", depending which model compression component you ar e using) directory. Therefore, you need to change "--model_dir ./models" into corresponding directory.

**Comment by Maximilianxu** [comment]
Hi, I have a similar issue.
`net_input = tf.get_collection(FLAGS.input_coll)[0]` 
`IndexError: list index out of range`
I use the UniformQuantizationLearner to quantize the Lenet(cifar-10) and then tried to convert it to `.tflite` format using `export_pb_tflite_models.py` with the following command:
`python tools/conversion/export_pb_tflite_models.py --model_dir ./uql_quant_eval_models  --quantize True --input_coll inputs--output_coll outputs`,
where 'uql_quant_eval_models' is the directory I used to save the eval graph with `self.saver_eval.save(self.sess_eval, 'uql_quant_eval_models/')` in the function `UniformQuantizationLearner.__restore_model()` (I just modified it to save the eval graph too).
However, the above issuse seems to cannot find the input tensors collection given the name 'inputs'. I also tried '--inputs data/IteratorGetNext' which I found in the eval graph shown in Tensorboard and it didn't work either. 
So, how to solve this? Thanks!

**Comment by Maximilianxu** [comment]
> em.. I want to export *.pb & *.tflite models from checkpoint files, so I run this command according the tutorial:
> python tools/conversion/export_pb_tflite_models.py 
> --model_dir ./models 
> --input_coll inputs 
> --output_coll outputs 
> --quantize True
> but I got an error `local variable 'file_path' referenced before assignment`
> the files in ./models:
> models
> ├── checkpoint
> ├── model.ckpt-97656.data-00000-of-00001
> ├── model.ckpt-97656.index
> └── model.ckpt-97656.meta
> So, can you give any idea about this?

The regex used in 'export_pb_tflite_models.py' (Line 40) cannot find the 'meta' file. I just modified it to `.meta$` and `file_path` can be found. Also, the 'models' dir have the checkpoints of the full precision model (I think you get it from the pretrained models from Tencent). To use the quantized one, you have to  use a directory where quantized model locates.

**Comment by jiaxiang-wu** [comment]
@wangxianrui @Maximilianxu 
1. `tools/conversion/export_pb_tflite_models.py` is for compressed models obtain via channel pruning based algorithms, *i.e.* `ChannelPrunedLearner` and `DisChnPrunedLearner`. For quantized models, use `tools/conversion/export_quant_tflite_model.py` instead.
2. To be able export a TF-Lite model, you need to use TensorFlow's quantization-aware training API, as supported in the `UniformQuantTFLearner`. Please, make sure that you are using the correct model compression components.

**Comment by Maximilianxu** [comment]
@jiaxiang-wu 
After using `UniformQuantTFLearner`, the eval graph is stored in 'models_uqtf' directory. Therefore, to quantize the model, I used the following command:
`python tools/conversion/export_quant_tflite_model.py \
--model_dir ./models_uqtf \
--input_coll inputs \
--output_coll outputs \
--enbl_post_quant True
` from the current docs.
Still,  it shows the following error:
`Traceback (most recent call last):
  File "tools/conversion/export_quant_tflite_model.py", line 271, in <module>
    tf.app.run()
  File "/home/yorukid/miniconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tools/conversion/export_quant_tflite_model.py", line 249, in main
    input_name, input_shape = get_input_name_n_shape(file_path_meta)
  File "tools/conversion/export_quant_tflite_model.py", line 63, in get_input_name_n_shape
    net_input = tf.get_collection(FLAGS.input_coll)[0]
IndexError: list index out of range
`.
What I used to train the LeNet-CIFAR10 is `python ./nets/lenet_at_cifar10_run.py --learner uniform-tf --data_dir_local data/cifar-10/cifar-10-binary`. It seems that `export_quant_tflite_model.py` cannot find the input and the output collections given the name. So, how to give these names? Could you please give some details about that? Thanks.

**Comment by jiaxiang-wu** [comment]
@Maximilianxu 
Please make sure you are using the correct checkpoint files for exporting to TF-Lite:
* The training graph is stored in the directory specified by `uqtf_save_path`, which is "./models_uqtf" by default. The graph and variables will be saved periodically during the training and after the training is completed.
* The evaluation graph is stored in the directory specified by `uqtf_save_path_eval`, which is "./models_uqtf_eval" by default. The graph and variables will only be saved after the training is completed.

**Comment by Maximilianxu** [comment]
> @Maximilianxu
> Sorry, our fault. The documentation is a bit out-of-date. You do not need to override the default values of `input_coll` and `output_coll`. To export, use this command:
> 
> ```shell
> $ python tools/conversion/export_quant_tflite_model.py \
>    --model_dir ./models_uqtf_eval
> ```
> 
> For MobileNet-v1/v2, this should work. For ResNet models, since TensorFlow's quantization API may not be able to recognize all operations that should be quantized (at least for TensorFlow-1.10.0), you need to append `--enbl_post_quant` to the end of conversion command:
> 
> ```shell
> $ python tools/conversion/export_quant_tflite_model.py \
>     --model_dir ./models_uqtf_eval \
>     --enbl_post_quant
> ```

- [ ] 

- [ ] 

It works! Thanks. (手动比心)

**Comment by jiaxiang-wu** [comment]
You're welcome. We will fix the documentation issue ASAP.

**Comment by jiaxiang-wu** [comment]
Resolved in the pull request #70
