### ISSUE TITLE
Question about transforming the quantized model to '.tflite' format

### ISSUE THREAD

**Issue by Maximilianxu** [Tencent/PocketFlow#63]
`net_input = tf.get_collection(FLAGS.input_coll)[0]
IndexError: list index out of range`

I used the UniformQuantizationLearner to quantize the Lenet(cifar-10) and then tried to convert it to `.tflite` format using export_pb_tflite_models.py with the following command:
`python tools/conversion/export_pb_tflite_models.py --model_dir ./uql_quant_eval_models --quantize True --input_coll inputs--output_coll outputs`,
where 'uql_quant_eval_models' is the directory I used to save the eval graph with `self.saver_eval.save(self.sess_eval, 'uql_quant_eval_models/')` in the function `UniformQuantizationLearner.__save_model()` (I just modified it to save the eval graph too).
However, the above issuse seems to cannot find the input tensors collection given the name 'inputs'. I also tried `--inputs data/IteratorGetNext` which I found in the eval graph shown in Tensorboard and it didn't work either.
So, how to solve this? Thanks!

**Comment by jiaxiang-wu** [comment]
1. `tools/conversion/export_pb_tflite_models.py` is for compressed models obtain via channel pruning based algorithms, *i.e.* `ChannelPrunedLearner` and `DisChnPrunedLearner`. For quantized models, use `tools/conversion/export_quant_tflite_model.py` instead.
2. To be able export a TF-Lite model, you need to use TensorFlow's quantization-aware training API, as supported in the `UniformQuantTFLearner`. You are using the wrong model compression components.

**Comment by jiaxiang-wu** [comment]
1. The documentation issue will be fixed ASAP.
2. In `UniformQuantLearner`, we can control the bit-width of each layer, so that we can see how well RL can optimize the bit-width allocation strategy, while in `UniformQuantTFLearner`, all layers' bit-width must be the same. If the variable bit-width allocation strategy can achieve superior performance than the uniform strategy (all layers use the same bit-width), maybe it will innovate some new inference framework to be developed to support this variable bit-width quantized network.

**Comment by jiaxiang-wu** [comment]
Doc needs revision: wrong model conversion command for quantized models.

**Comment by Maximilianxu** [comment]
@jiaxiang-wu 
Thanks, I see. Tensorflow only has a fixed API to perform an uniform quantization strategy to convert the model. You mean even though `UniformQuantLearner` could get better results (more flexible strategy), we still cannot use it yet in the production environment with Tensorflow, right?

**Comment by jiaxiang-wu** [comment]
Yes, TensorFlow Lite only supports 8-bit quantized models. Actually, `UniformQuantLearner` is more like a research-oriented component, since it is more flexible.
