### ISSUE TITLE
Question on 'uniform_quantization_tf'

### ISSUE THREAD

**Issue by wangxianrui** [Tencent/PocketFlow#68]
In the source code of ` leaners/uniform_quantization_tf/learner.py`,  using  tensorflow's quantization-aware to creat training graph:
```
tf.contrib.quantize.experimental_create_training_graph(
        weight_bits=FLAGS.uqtf_weight_bits,
        activation_bits=FLAGS.uqtf_activation_bits,
        quant_delay=FLAGS.uqtf_quant_delay,
        freeze_bn_delay=FLAGS.uqtf_freeze_bn_delay,
        scope=self.model_scope_quan)
```
but I don not find the value of  'input_graph',  so I am so confused about how i can work, 
... Maybe this is kind of stupid, I am not familiar with tensorflow  ==

**Comment by jiaxiang-wu** [comment]
If the `input_graph` argument is not specified, its default value, which is "None", will take effect and the default graph will be used. The default graph is defined in the code block starting from here:
[https://github.com/Tencent/PocketFlow/blob/master/learners/uniform_quantization_tf/learner.py#L142](https://github.com/Tencent/PocketFlow/blob/master/learners/uniform_quantization_tf/learner.py#L142)

**Comment by wangxianrui** [comment]
I just looked at  'quantize_graph.py',  so ... , sorry to bother you
