### ISSUE TITLE
apply in 1D convolutions

### ISSUE THREAD

**Issue by 1448643857** [Tencent/PocketFlow#78]
Hi,I want to use this  to train 1D convolution model,I  should modify where ,can you give me some suggestions?

**Comment by jiaxiang-wu** [comment]
Which model compression component are you planning to use?

**Comment by 1448643857** [comment]
Hi，I want to use learner channel,my job is using deep learning in Signal detection,and I want use PocketFlow to compress my model,but it's 1D ,but I don't know how to Implemente,so I questioned in here.

**Comment by jiaxiang-wu** [comment]
`ChannelPrunedLearner` does not support 1D convolution. To use channel pruning algorithm, you need to modify the channel selection part (selection channels by solving a LASSO problem) to fit the 1D convolution case.

**Comment by 1448643857** [comment]
ok,thank you very much.
