### ISSUE TITLE
About support for 3D convolutions?

### ISSUE THREAD

**Issue by yyjabidintg** [Tencent/PocketFlow#79]
I was wondering if PocketFlow supports 3D convolutions.like the C3D model. can we use it to compress the C3D model(like 3D resnet)?
Thankes for your help.

**Comment by jiaxiang-wu** [comment]
Similar with issue #78, although it is for 1D convolution.
For now, channel pruning based components, *e.g.* `ChannelPrunedLearner`, do not support 3D convolution. To use channel pruning algorithm, you need to modify the channel selection part (selection channels by solving a LASSO problem) to fit the 3D convolution case.
