### ISSUE TITLE
Not sure if this is issue: Took more than 20 hours for pruning, and still running. 

### ISSUE THREAD

**Issue by jzlwlhao** [Tencent/PocketFlow#98]
Commend:./scripts/run_local.sh nets/resnet_at_ilsvrc12_run.py --learner channel

Looks like it is running normally, but spent more than 20 hours.

INFO:tensorflow:Feature map reconstruction time cost: 1.5722044709837064s
INFO:tensorflow:Prune model/resnet_model/conv2d_15/Conv2D c_in from 256 to 70
INFO:tensorflow:father conv model/resnet_model/conv2d_14/Conv2D
INFO:tensorflow:father conv input Tensor("model/resnet_model/Relu_10:0", shape=(64, 14, 14, 256), dtype=float32)
INFO:tensorflow:Channel pruning the model/resnet_model/conv2d_15/Conv2D layer,       the pruning rate is 0.2734375
INFO:tensorflow:Actural preserv ratio: 0.2734375
INFO:tensorflow:state is [[0.8        1.         0.5        0.0625     0.0625     1.
  0.23131373 0.05442177]]
INFO:tensorflow:RL choosed preserv ratio: [[0.26442486]]
INFO:tensorflow:preserve ratio before constraint [[0.26442486]]
INFO:tensorflow:max_reduced_flops 423833628.7179487
INFO:tensorflow:desired_preserce 913203200.0
INFO:tensorflow:this flops 6422528.0
INFO:tensorflow:recommand action 76.46021120536396
INFO:tensorflow:preserve ratio after constraint 0.2644248604774475
INFO:tensorflow:pruning kernel
INFO:tensorflow:approximating residual branch diff
INFO:tensorflow:approximating residual branch diff
INFO:tensorflow:computing pruned kernel
INFO:tensorflow:pruned channel selecting
INFO:tensorflow:Channel selection time cost: 14.02673977194354s
INFO:tensorflow:Feature map reconstructing
INFO:tensorflow:Feature map reconstruction time cost: 0.5076901899883524s
INFO:tensorflow:Prune model/resnet_model/conv2d_16/Conv2D c_in from 256 to 67
INFO:tensorflow:Channel pruning the model/resnet_model/conv2d_16/Conv2D layer,       the pruning rate is 0.26171875
INFO:tensorflow:Actural preserv ratio: 0.26171875
INFO:tensorflow:state is [[0.85       1.         0.5        0.0625     0.0625     1.
  0.23205877 0.48979592]]
INFO:tensorflow:RL choosed preserv ratio: [[0.2642664]]
INFO:tensorflow:preserve ratio before constraint [[0.2642664]]
INFO:tensorflow:max_reduced_flops 423818226.03044933
INFO:tensorflow:desired_preserce 913203200.0
INFO:tensorflow:this flops 15267839.064844945
INFO:tensorflow:recommand action 32.31758919927788
INFO:tensorflow:preserve ratio after constraint 0.26426640152931213
INFO:tensorflow:pruning kernel
INFO:tensorflow:computing pruned kernel
INFO:tensorflow:pruned channel selecting
INFO:tensorflow:Channel selection time cost: 37.22164929204155s
INFO:tensorflow:Feature map reconstructing
INFO:tensorflow:Feature map reconstruction time cost: 1.7293230179930106s
INFO:tensorflow:Prune model/resnet_model/conv2d_17/Conv2D c_in from 256 to 67
INFO:tensorflow:Channel pruning the model/resnet_model/conv2d_17/Conv2D layer,       the pruning rate is 0.26171875
INFO:tensorflow:Actural preserv ratio: 0.26171875
INFO:tensorflow:state is [[0.9        1.         1.         0.0625     0.0625     0.5
  0.23205034 0.97959184]]
INFO:tensorflow:RL choosed preserv ratio: [[0.2641434]]
INFO:tensorflow:preserve ratio before constraint [[0.2641434]]
INFO:tensorflow:max_reduced_flops 423780181.1178297
INFO:tensorflow:desired_preserce 913203200.0
INFO:tensorflow:this flops 130733568.0
INFO:tensorflow:recommand action 4.007810977728656
INFO:tensorflow:preserve ratio after constraint 0.2641434073448181
INFO:tensorflow:pruning kernel

**Comment by jiaxiang-wu** [comment]
@psyyz10 Could you please take a look and see whether this time consumption is normal?

**Comment by psyyz10** [comment]
@jzlwlhao  It's normal. There will be 200 roll outs for an auto selection of channel pruning. The process of resnet on Imagenet is slow. If you choose the `auto` mode of channel pruning, please set `--ddpg_noise_std_init=0.5`.
